/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three'
export function T() {
  const { nodes, materials } = useGLTF('/tree (8)-compressed.glb') as any;

  const treeRef = useRef<THREE.Group>(null);
  
    useFrame((state) => {
      if (treeRef.current) {
        const time = state.clock.getElapsedTime();
        
        // Fast swaying motion (multiplied by 4.5 for speed)
        treeRef.current.rotation.x = Math.sin(time * 1.9) * 0.03;
        
      }
    });
  
  return (
    <group  ref={treeRef}  position={[-15, 0, -150]} 
      scale={[0.19, 0.19, 0.19]}  dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials.branches}
        position={[-1.274, 48.363, 2.729]}
        scale={48.363}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_1.geometry}
        material={materials.leaves}
        position={[-1.032, 55.485, 4.522]}
        scale={49.35}
      />
    </group>
  )
}

useGLTF.preload('/tree (8)-compressed.glb')
