/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { Edges } from '@react-three/drei'

type TreeProps = {
  position?: [number, number, number]
  scale?: [number, number, number]
}

export function Trees({ position = [-15, 0, -160], scale = [0.19, 0.19, 0.19] }: TreeProps) {
  const { nodes, materials } = useGLTF('/tree (4)_compressed.glb') as any;
  
  // 1. Create a reference for the entire tree group
  // const treeRef = useRef<THREE.Group>(null);

  // useFrame((state) => {
  //   if (treeRef.current) {
  //     const time = state.clock.getElapsedTime();
      
  //     // Fast swaying motion (multiplied by 4.5 for speed)
  //     treeRef.current.rotation.x = Math.sin(time * 1.9) * 0.03;
  //   }
  // });

  return (
    // 2. Attach the ref, position, and scale to the group container
    <group 
      // ref={treeRef} 
      position={position} 
      scale={scale} 
      dispose={null}
    >
      {/* Branches / Trunk */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials.branches}
       
      />
       <Edges color="111111"/>
      {/* Leaves */}
      <mesh 
        castShadow 
        receiveShadow 
        geometry={nodes.mesh_1.geometry} 
        material={materials.leaves} 
      />
    </group>
  )
}

useGLTF.preload('/tree (4)_compressed.glb')