/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table() {
  const { nodes, materials } = useGLTF('/table.glb') as any;
  return (
    <group  dispose={null} position={[0, 1000, 0]} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.001}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['3DGeom-1'].geometry}
            material={materials['[Wood Bamboo]']}
            scale={25.4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['3DGeom-2'].geometry}
            material={materials['[Carpet Loop Pattern]']}
            scale={25.4}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/table.glb')
