/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}
export function COF1({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props) {
  const { nodes, materials } = useGLTF('/COF_1.glb') as any;
  return (
    <group {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[-78,0,223]} rotation={[0, -Math.PI / 1.59, 0, ]} >
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-78" scale={0.001}>
            <group
              name="Active_View"
              position={[58490.48, -11773.229, 26885.846]}
              rotation={[0.308, 1.077, 1.224]}
              scale={1000}
            />
            {visibleFloors.includes('2ND') && (
            <group name="2ndfloor" position={[-3988.578, -14066.079, 4058]} scale={25.4}>
              <mesh
                name="3DGeom-1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-1'].geometry}
                material={materials['[0095_LightBlue]']}
              />
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials['[White Square Tile]1']}
              />
              <mesh
                name="3DGeom-4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-4'].geometry}
                material={materials['[0117_GhostWhite]']}
              />
              <mesh
                name="3DGeom-5"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-5'].geometry}
                material={materials['[0131_Silver]']}
              />
              <group position={[3.937, 964.567, 63.74]}>
                <mesh
                  name="3DGeom-6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 830.709, 63.74]}>
                <mesh
                  name="3DGeom-6_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_1'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 696.85, 63.74]}>
                <mesh
                  name="3DGeom-6_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_2'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_2'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 562.992, 63.74]}>
                <mesh
                  name="3DGeom-6_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_3'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_3'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 429.134, 63.74]}>
                <mesh
                  name="3DGeom-6_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_4'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_4'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 295.276, 63.74]}>
                <mesh
                  name="3DGeom-6_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_5'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_5'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 161.417, 63.74]}>
                <mesh
                  name="3DGeom-6_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_6'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_6'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 27.559, 63.74]}>
                <mesh
                  name="3DGeom-6_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_7'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_7'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group
                position={[273.622, 1047.874, 59.055]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[273.622, 574.173, 59.055]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[273.622, 306.457, 59.055]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[273.622, 244.724, 59.055]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 1022.008, 78.346]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.039, 1]}>
                <mesh
                  name="3DGeom-38"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[279.528, 921.26, 78.346]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.467, 1]}>
                <mesh
                  name="3DGeom-38_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_1'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[279.528, 787.402, 78.346]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.467, 1]}>
                <mesh
                  name="3DGeom-38_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_2'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_2'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[279.528, 661.417, 78.346]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.039, 1]}>
                <mesh
                  name="3DGeom-38_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_3'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_3'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[279.528, 519.685, 78.346]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.467, 1]}>
                <mesh
                  name="3DGeom-38_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_4'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_4'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[279.528, 393.701, 78.346]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.039, 1]}>
                <mesh
                  name="3DGeom-38_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_5'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_5'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[279.528, 218.858, 78.346]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.039, 1]}>
                <mesh
                  name="3DGeom-38_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_6'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_6'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[59.055, 1210.63, 112.52]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[98.425, 1210.63, 73.15]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_1'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[59.055, 1210.63, 33.78]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_2'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[59.055, 1210.63, 73.15]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_3'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[98.425, 1210.63, 112.52]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_4'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[98.425, 1210.63, 33.78]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_5'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[138.679, 851.047, 36.742]} rotation={[0, 0, Math.PI]} scale={0.1}>
                <mesh
                  name="3DGeom-65"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-65'].geometry}
                  material={materials['[0046_Gold]']}
                />
              </group>
              <group position={[60.139, 583.526, 15.748]} rotation={[0, 0, Math.PI]} scale={0.1}>
                <mesh
                  name="3DGeom-65_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-65_1'].geometry}
                  material={materials['[0046_Gold]']}
                />
              </group>
              <group position={[122.595, 306.068, 15.748]} rotation={[0, 0, Math.PI]} scale={0.1}>
                <mesh
                  name="3DGeom-65_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-65_2'].geometry}
                  material={materials['[0046_Gold]']}
                />
              </group>
              <group position={[80.5, 850.592, 15.748]}>
                <mesh
                  name="3DGeom-68"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-69"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-69'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[80.5, 566.143, 15.748]}>
                <mesh
                  name="3DGeom-68_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_1'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-69_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-69_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[80.5, 43.741, 15.748]}>
                <mesh
                  name="3DGeom-68_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_2'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-69_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-69_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[80.5, 307.993, 15.748]}>
                <mesh
                  name="3DGeom-68_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_3'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-69_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-69_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[122.595, 44.415, 15.748]} rotation={[0, 0, Math.PI]} scale={0.1}>
                <mesh
                  name="3DGeom-65_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-65_3'].geometry}
                  material={materials['[0046_Gold]']}
                />
              </group>
              <group name="Rail_TB" position={[163.897, 1081.969, 15.748]}>
                <group name="Rail" position={[0, 0.709, 17.52]}>
                  <mesh
                    name="3DGeom-77"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-77'].geometry}
                    material={materials['*']}
                  />
                  <mesh
                    name="3DGeom-78"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-78'].geometry}
                    material={materials['[Wood Veneer 02]']}
                  />
                </group>
                <group name="Pole2" position={[-1113.596, -3870.422, -175.512]}>
                  <group>
                    <mesh
                      name="3DGeom-79"
                      castShadow
                      receiveShadow
                      geometry={nodes['3DGeom-79'].geometry}
                      material={materials['*']}
                    />
                    <mesh
                      name="3DGeom-80"
                      castShadow
                      receiveShadow
                      geometry={nodes['3DGeom-80'].geometry}
                      material={materials['[Wood Veneer 02]']}
                    />
                  </group>
                  <group position={[2231.129, 7812.143, 0]} rotation={[0, 0, -Math.PI]}>
                    <mesh
                      name="3DGeom-79_1"
                      castShadow
                      receiveShadow
                      geometry={nodes['3DGeom-79_1'].geometry}
                      material={materials['*']}
                    />
                    <mesh
                      name="3DGeom-80_1"
                      castShadow
                      receiveShadow
                      geometry={nodes['3DGeom-80_1'].geometry}
                      material={materials['[Wood Veneer 02]']}
                    />
                  </group>
                </group>
              </group>
            </group>
            )}
             {visibleFloors.includes('roof') && (

            <group name="roof" position={[-5488.578, -15566.079, 8116]} scale={25.4}>
              <mesh
                name="3DGeom-83"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-83'].geometry}
                material={materials['[0095_LightBlue]']}
              />
            </group>
               )}
             {visibleFloors.includes('1ST') && (
            <group name="1stfloor" position={[-3988.578, -14066.079, 0]} scale={25.4}>
              <mesh
                name="3DGeom-84"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-84'].geometry}
                material={materials['[0095_LightBlue]']}
              />
              <mesh
                name="3DGeom-85"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-85'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-86"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-86'].geometry}
                material={materials['[White Square Tile]1']}
              />
              <mesh
                name="3DGeom-87"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-87'].geometry}
                material={materials['[0131_Silver]']}
              />
              <group position={[3.937, 964.567, 63.74]}>
                <mesh
                  name="3DGeom-6_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_8'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_8'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_8'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 830.709, 63.74]}>
                <mesh
                  name="3DGeom-6_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_9'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_9'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_9'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 698.819, 63.74]}>
                <mesh
                  name="3DGeom-6_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_10'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_10'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_10'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 562.992, 63.74]}>
                <mesh
                  name="3DGeom-6_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_11'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_11'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_11'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 429.134, 63.74]}>
                <mesh
                  name="3DGeom-6_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_12'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_12'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_12'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group position={[3.937, 295.276, 63.74]}>
                <mesh
                  name="3DGeom-6_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_13'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_13'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
                <mesh
                  name="3DGeom-8_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_13'].geometry}
                  material={materials['WB Glazing']}
                />
              </group>
              <group
                position={[273.622, 1047.874, 59.055]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31_4'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[273.622, 708.031, 59.055]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31_5'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[273.622, 306.457, 59.055]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31_6'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[273.622, 94.488, 59.055]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30_7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31_7'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[279.528, 1022.008, 78.346]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-38_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_7'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_7'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[279.528, 925.197, 78.346]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-38_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_8'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_8'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_8'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[279.528, 792.953, 78.346]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-38_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_9'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_9'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_9'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[279.528, 657.48, 78.346]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-38_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_10'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_10'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_10'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[279.528, 523.622, 78.346]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-38_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_11'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_11'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_11'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[279.528, 391.378, 78.346]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-38_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_12'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-39_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_12'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-40_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_12'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[59.055, 1210.63, 33.78]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_6'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[98.425, 1210.63, 33.78]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_7'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[59.055, 1210.63, 73.15]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_8'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[98.425, 1210.63, 73.15]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_9'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[59.055, 1210.63, 112.52]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_10'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[98.425, 1210.63, 112.52]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-59_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-59_11'].geometry}
                  material={materials['[0095_LightBlue]']}
                />
              </group>
              <group position={[118.45, 855.828, 15.748]} rotation={[0, 0, Math.PI]} scale={0.1}>
                <mesh
                  name="3DGeom-65_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-65_4'].geometry}
                  material={materials['[0046_Gold]']}
                />
              </group>
              <group position={[76.144, 307.795, 15.748]}>
                <mesh
                  name="3DGeom-68_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_4'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-69_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-69_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[76.144, 589.213, 15.748]}>
                <mesh
                  name="3DGeom-68_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_5'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-69_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-69_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[76.144, 857.677, 15.748]}>
                <mesh
                  name="3DGeom-68_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_6'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-69_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-69_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[123.439, 583.285, 15.748]} rotation={[0, 0, Math.PI]} scale={0.1}>
                <mesh
                  name="3DGeom-65_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-65_5'].geometry}
                  material={materials['[0046_Gold]']}
                />
              </group>
              <group position={[121.297, 311.437, 15.748]} rotation={[0, 0, Math.PI]} scale={0.1}>
                <mesh
                  name="3DGeom-65_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-65_6'].geometry}
                  material={materials['[0046_Gold]']}
                />
              </group>
              <group position={[4296.405, 376.058, 0]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-147"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-147'].geometry}
                  material={materials['[White Square Tile]']}
                />
                <group name="Rail_TB_1" position={[763.756, 4139.673, 25.591]}>
                  <group
                    name="Pole2_1"
                    position={[-3928.268, 1106.431, -25.591]}
                    rotation={[0, 0, -Math.PI / 2]}>
                    <group>
                      <mesh
                        name="3DGeom-148"
                        castShadow
                        receiveShadow
                        geometry={nodes['3DGeom-148'].geometry}
                        material={materials['*']}
                      />
                      <mesh
                        name="3DGeom-149"
                        castShadow
                        receiveShadow
                        geometry={nodes['3DGeom-149'].geometry}
                        material={materials['[Wood Veneer 02]']}
                      />
                    </group>
                    <group position={[4563.843, 5935.822, 68.898]} rotation={[0, 0, 2.356]}>
                      <mesh
                        name="3DGeom-148_1"
                        castShadow
                        receiveShadow
                        geometry={nodes['3DGeom-148_1'].geometry}
                        material={materials['*']}
                      />
                      <mesh
                        name="3DGeom-149_1"
                        castShadow
                        receiveShadow
                        geometry={nodes['3DGeom-149_1'].geometry}
                        material={materials['[Wood Veneer 02]']}
                      />
                    </group>
                    <group position={[-994.351, 7494.656, 68.898]} rotation={[0, 0, -2.356]}>
                      <mesh
                        name="3DGeom-148_2"
                        castShadow
                        receiveShadow
                        geometry={nodes['3DGeom-148_2'].geometry}
                        material={materials['*']}
                      />
                      <mesh
                        name="3DGeom-149_2"
                        castShadow
                        receiveShadow
                        geometry={nodes['3DGeom-149_2'].geometry}
                        material={materials['[Wood Veneer 02]']}
                      />
                    </group>
                    <group position={[11.811, 11.811, 147.638]}>
                      <mesh
                        name="3DGeom-148_3"
                        castShadow
                        receiveShadow
                        geometry={nodes['3DGeom-148_3'].geometry}
                        material={materials['*']}
                      />
                      <mesh
                        name="3DGeom-149_3"
                        castShadow
                        receiveShadow
                        geometry={nodes['3DGeom-149_3'].geometry}
                        material={materials['[Wood Veneer 02]']}
                      />
                    </group>
                  </group>
                  <group name="Rail_1" position={[0, 0.457, 17.611]}>
                    <mesh
                      name="3DGeom-156"
                      castShadow
                      receiveShadow
                      geometry={nodes['3DGeom-156'].geometry}
                      material={materials['*']}
                    />
                    <mesh
                      name="3DGeom-157"
                      castShadow
                      receiveShadow
                      geometry={nodes['3DGeom-157'].geometry}
                      material={materials['[Wood Veneer 02]']}
                    />
                  </group>
                </group>
              </group>
            </group>
             )}

          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/COF_1.glb')
