/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}

export function COF2({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props) {
  const { nodes, materials } = useGLTF('/COF 2.glb') as any;
  return (
    <group  {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[-32,0,232]} rotation={[0, -Math.PI / 1.59, 0, ]} >
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-85" scale={0.001}>
            <group
              name="Active_View"
              position={[-27093.24, 14061.799, 11904.113]}
              rotation={[0.618, -1.274, -0.931]}
              scale={1000}
            />
             {visibleFloors.includes('2ND') && (
            <group name="2nd" position={[-8390.259, -19233.402, 3448]} scale={25.4}>
              <mesh
                name="3DGeom-1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-1'].geometry}
                material={materials.magentaa}
              />
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials['[Concrete Pavers Block Multi]']}
              />
              <mesh
                name="3DGeom-4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-4'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-5"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-5'].geometry}
                material={materials['[0117_GhostWhite]']}
              />
              <mesh
                name="3DGeom-6"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-6'].geometry}
                material={nodes['3DGeom-6'].material}
              />
              <group position={[7.874, 94.488, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[275.591, 206.969, 57.087]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[275.591, 501.693, 57.087]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[275.591, 674.921, 57.087]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 287.402, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 421.26, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 594.488, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[275.591, 978.622, 57.087]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 1060.367, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_4'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 1194.226, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_5'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 1405.512, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_6'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[275.591, 1273.346, 57.087]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_4'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[275.591, 1325.079, 57.087]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_5'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 1385.827, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 1212.598, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_1'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_1'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 1039.37, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_2'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_2'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_2'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 614.173, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_3'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_3'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_3'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 440.945, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_4'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_4'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_4'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 267.717, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_5'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_5'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_5'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[74.803, 7.874, 75.728]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.667, 1, 1]}>
                <mesh
                  name="3DGeom-33_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_6'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_6'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_6'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[85.389, 389.835, 15.748]}>
                <mesh
                  name="3DGeom-54"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[89.45, 557.195, 15.748]}>
                <mesh
                  name="3DGeom-54_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_1'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[31.907, 1150.768, 15.748]}>
                <mesh
                  name="3DGeom-54_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_2'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[49.956, 1107.774, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-54_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_3'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[206.554, 1262.076, 15.748]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-54_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_4'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[67.341, 1320.648, 15.748]}>
                <mesh
                  name="3DGeom-54_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_5'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[89.17, 221.742, 15.748]}>
                <mesh
                  name="3DGeom-54_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_6'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[29.376, 130.899, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-54_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_7'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[275.591, 926.89, 57.087]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_6'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[48.704, 1052.39, 15.748]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-72"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[121.92, 561.84, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_1'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[78.708, 1157.191, 15.748]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-72_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_2'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[106.277, 1326.94, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_3'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[125.957, 226.087, 15.549]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_4'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[133.036, 390.253, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_5'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[159.789, 1264.752, 15.748]}>
                <mesh
                  name="3DGeom-72_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_6'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
            </group>
             )}
              {visibleFloors.includes('roof') && (
            <group name="roof" position={[-9390.259, -20233.402, 6896]} scale={25.4}>
              <mesh
                name="3DGeom-79"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-79'].geometry}
                material={materials['[0117_GhostWhite]']}
              />
              <mesh
                name="3DGeom-80"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-80'].geometry}
                material={materials['[0023_FireBrick]']}
              />
              <group position={[7.874, 7.874, 0]}>
                <mesh
                  name="3DGeom-81"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-81'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[488.189, 7.874, 0]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-81_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-81_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[582.677, 1685.039, 0]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-81_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-81_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[7.874, 1685.039, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-81_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-81_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group name="m" position={[-97.008, -3.976, -271.496]}>
                <mesh
                  name="3DGeom-85"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-85'].geometry}
                  material={materials['[0023_FireBrick]']}
                />
              </group>
              <group position={[-0.846, -0.88, 19.685]}>
                <mesh
                  name="3DGeom-86"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-86'].geometry}
                  material={materials['[0023_FireBrick]']}
                />
              </group>
            </group>
              )}
              {visibleFloors.includes('1ST') && (
            <group name="1st" position={[-8390.259, -19233.402, 0]} scale={25.4}>
              <mesh
                name="3DGeom-87"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-87'].geometry}
                material={materials.magentaa}
              />
              <mesh
                name="3DGeom-88"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-88'].geometry}
                material={materials.magentaa}
              />
              <mesh
                name="3DGeom-89"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-89'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-90"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-90'].geometry}
                material={materials['[Concrete Pavers Block Multi]']}
              />
              <mesh
                name="3DGeom-91"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-91'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-92"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-92'].geometry}
                material={materials['[0117_GhostWhite]']}
              />
              <group position={[275.591, 206.969, 57.087]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_7'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[275.591, 501.693, 57.087]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_8'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_8'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[275.591, 674.921, 57.087]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_9'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_9'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[275.591, 1100.118, 57.087]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_10'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_10'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[275.591, 1273.346, 57.087]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_11'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_11'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[275.591, 1446.575, 57.087]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-9_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_12'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-10_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_12'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 287.402, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_7'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 421.26, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_8'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_8'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 594.488, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_9'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_9'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 1019.685, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_10'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_10'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 1191.601, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_11'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_11'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[279.528, 1366.142, 75.079]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={[0.667, 0.973, 1]}>
                <mesh
                  name="3DGeom-7_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_12'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_12'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[-390.991, -335.883, 31.57]}>
                <mesh
                  name="3DGeom-117"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-117'].geometry}
                  material={materials.magentaa}
                />
              </group>
              <group position={[-390.991, -162.655, 31.57]}>
                <mesh
                  name="3DGeom-117_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-117_1'].geometry}
                  material={materials.magentaa}
                />
              </group>
              <group position={[-390.991, 10.574, 31.57]}>
                <mesh
                  name="3DGeom-117_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-117_2'].geometry}
                  material={materials.magentaa}
                />
              </group>
              <group position={[-390.991, 183.802, 31.57]}>
                <mesh
                  name="3DGeom-117_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-117_3'].geometry}
                  material={materials.magentaa}
                />
              </group>
              <group position={[7.874, 1385.827, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_7'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_7'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_7'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 1212.598, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_8'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_8'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_8'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 1039.37, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_9'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_9'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_9'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 614.173, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_10'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_10'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_10'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 440.945, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_11'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_11'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_11'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 267.717, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_12'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_12'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_12'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[7.874, 94.488, 75.728]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-33_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_13'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_13'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_13'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[74.803, 7.874, 75.728]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.667, 1, 1]}>
                <mesh
                  name="3DGeom-33_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_14'].geometry}
                  material={materials['[0043_SaddleBrown]1']}
                />
                <mesh
                  name="3DGeom-34_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34_14'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-35_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35_14'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[85.508, 1170.326, 15.748]}>
                <mesh
                  name="3DGeom-54_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_8'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_8'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[67.72, 218.264, 15.748]}>
                <mesh
                  name="3DGeom-54_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_9'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_9'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[85.508, 1358.121, 15.748]}>
                <mesh
                  name="3DGeom-54_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_10'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_10'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[85.508, 987.727, 15.748]}>
                <mesh
                  name="3DGeom-54_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_11'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_11'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[67.72, 402.477, 15.748]}>
                <mesh
                  name="3DGeom-54_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_12'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_12'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[67.72, 571.375, 15.748]}>
                <mesh
                  name="3DGeom-54_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-54_13'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-55_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-55_13'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[133.769, 987.652, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_7'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[135.791, 577.516, 45.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_8'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[112.034, 214.193, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_9'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[127.64, 1164.869, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_10'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[135.057, 1344.362, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_11'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group position={[103.685, 405.428, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-72_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-72_12'].geometry}
                  material={materials['[0047_Khaki]']}
                />
              </group>
              <group
                position={[263.819, 17.243, 1.89]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[0.52, 1, 1]}>
                <mesh
                  name="3DGeom-163"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-163'].geometry}
                  material={materials['[Basic Tile]']}
                />
                <mesh
                  name="3DGeom-164"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-164'].geometry}
                  material={materials['[Tile Ceramic Multi]']}
                />
                <mesh
                  name="3DGeom-165"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-165'].geometry}
                  material={materials.magentaa}
                />
                <mesh
                  name="3DGeom-166"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-166'].geometry}
                  material={materials.magentaa}
                />
              </group>
              <group
                position={[1728.386, 1396.442, 0]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[0.645, 1, 1]}>
                <mesh
                  name="3DGeom-167"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-167'].geometry}
                  material={materials['[Tile Ceramic Multi]']}
                />
                <mesh
                  name="3DGeom-168"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-168'].geometry}
                  material={materials['[Basic Tile]']}
                />
                <mesh
                  name="3DGeom-169"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-169'].geometry}
                  material={materials['[Granite Light Gray]']}
                />
                <mesh
                  name="3DGeom-170"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-170'].geometry}
                  material={materials['[Basic Tile]']}
                />
              </group>
              <group position={[964.606, 455.881, 0]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-171"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-171'].geometry}
                  material={materials['[Basic Tile]']}
                />
              </group>
            </group>
            )}
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/COF 2.glb')
