/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}
export function COFLAB({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props){
  const { nodes, materials } = useGLTF('/COF_lab.glb') as any;
  return (
    <group  {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}   dispose={null} position={[-91,0,207]} rotation={[0, -Math.PI / 7.5, 0, ]} scale={[1.2,1,1.2]}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-20" scale={0.001}>
            <group
              name="Active_View"
              position={[11188.84, -38360.191, 14486.061]}
              rotation={[1.33, -0.218, -0.053]}
              scale={1000}
            />
              {visibleFloors.includes('1ST') && (
            <group name="1st" position={[5204, 0, 0]} scale={25.4}>
              <mesh
                name="3DGeom-1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-1'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials['[0093_AliceBlue]']}
              />
              <mesh
                name="3DGeom-4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-4'].geometry}
                material={materials['[0101_CornflowerBlue]']}
              />
              <group position={[-1776.186, -272.641, -116.118]} scale={[0.744, 1, 0.954]}>
                <mesh
                  name="3DGeom-5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[-1602.958, -549.494, -116.118]} scale={[0.744, 1, 0.954]}>
                <mesh
                  name="3DGeom-5_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[-1868.196, -547.953, -116.118]} scale={[0.993, 1, 0.954]}>
                <mesh
                  name="3DGeom-7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[-1776.186, -546.933, -116.118]} scale={[0.744, 1, 0.954]}>
                <mesh
                  name="3DGeom-5_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_2'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[925.039, 56.732, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[925.039, 262.717, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-9_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[444.173, 279.528, 15.748]}>
                <mesh
                  name="3DGeom-9_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[-86.993, 76.675, 15.748]}>
                <mesh
                  name="3DGeom-12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12'].geometry}
                  material={materials['[Wood Veneer 01]']}
                />
                <mesh
                  name="3DGeom-13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-13'].geometry}
                  material={materials['[Water Dark Blue]']}
                />
              </group>
              <group position={[57.22, 76.675, 15.748]}>
                <mesh
                  name="3DGeom-12_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12_1'].geometry}
                  material={materials['[Wood Veneer 01]']}
                />
                <mesh
                  name="3DGeom-13_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-13_1'].geometry}
                  material={materials['[Water Dark Blue]']}
                />
              </group>
              <group position={[199.936, 76.675, 15.748]}>
                <mesh
                  name="3DGeom-12_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12_2'].geometry}
                  material={materials['[Wood Veneer 01]']}
                />
                <mesh
                  name="3DGeom-13_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-13_2'].geometry}
                  material={materials['[Water Dark Blue]']}
                />
              </group>
            </group>
              )}
               {visibleFloors.includes('roof') && (
            <group name="roof" position={[17100, -500, 6286]} scale={25.4}>
              <mesh
                name="3DGeom-18"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-18'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-19"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-19'].geometry}
                material={materials['[0101_CornflowerBlue]']}
              />
              <mesh
                name="3DGeom-20"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-20'].geometry}
                material={materials['[0093_AliceBlue]']}
              />
              <group position={[-346.457, 0, -135.748]}>
                <mesh
                  name="3DGeom-21"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-21'].geometry}
                  material={materials['[0101_CornflowerBlue]']}
                />
              </group>
            </group>
             )}
               {visibleFloors.includes('2ND') && (
            <group name="2nd" position={[17600, 0, 2838]} scale={25.4}>
              <mesh
                name="3DGeom-22"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-22'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-23"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-23'].geometry}
                material={materials['[0093_AliceBlue]']}
              />
              <mesh
                name="3DGeom-24"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-24'].geometry}
                material={materials['[0101_CornflowerBlue]']}
              />
              <group position={[420.197, 59.055, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-9_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[437.008, 94.488, 69.449]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-26"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-26'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-27"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[437.008, 188.976, 69.449]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-26_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-26_1'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-27_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[437.008, 141.732, 69.449]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30'].geometry}
                  material={materials['[0093_AliceBlue]']}
                />
                <mesh
                  name="3DGeom-31"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31'].geometry}
                  material={materials['[0131_Silver]']}
                />
                <mesh
                  name="3DGeom-32"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-32'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[-1683.845, -838.306, -236.83]}>
                <mesh
                  name="3DGeom-33"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33'].geometry}
                  material={materials['[0023_FireBrick]']}
                />
              </group>
            </group>
               )}
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/COF_lab.glb')
