/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}

export function Infirmary({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props) {
  const { nodes, materials } = useGLTF('/Infirmary.glb') as any;
  return (
    <group {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[26,0,-105 ]} rotation={[0,-Math.PI / 1.6, 0, ]} scale={[1.2,1,1]}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-47" scale={0.001}>
            <group
              name="Active_View"
              position={[62329.23, 5849.635, 29835.395]}
              rotation={[-0.249, 1.157, 1.842]}
              scale={1000}
            />
             {visibleFloors.includes('1ST') && (
            <group name="1ST" position={[-8189.064, -18588.852, 0]} scale={25.4}>
              <mesh
                name="3DGeom-1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-1'].geometry}
                material={materials['*']}
              />
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials['[White Square Tile]1']}
              />
              <group position={[562.717, 464.449, 15.748]}>
                <mesh
                  name="3DGeom-3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-3'].geometry}
                  material={materials['[0032_Moccasin]']}
                />
                <mesh
                  name="3DGeom-4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-4'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[562.717, 500.433, 15.748]}>
                <mesh
                  name="3DGeom-3_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-3_1'].geometry}
                  material={materials['[0032_Moccasin]']}
                />
                <mesh
                  name="3DGeom-4_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-4_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[316.102, 205.157, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-3_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-3_2'].geometry}
                  material={materials['[0032_Moccasin]']}
                />
                <mesh
                  name="3DGeom-4_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-4_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[352.087, 205.157, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-3_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-3_3'].geometry}
                  material={materials['[0032_Moccasin]']}
                />
                <mesh
                  name="3DGeom-4_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-4_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[560.748, 1244.528, 63.74]} scale={[1, 1.364, 1]}>
                <mesh
                  name="3DGeom-11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-11'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[424.921, 1390.197, 63.74]} scale={[0.844, 1, 1]}>
                <mesh
                  name="3DGeom-13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-13'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
                <mesh
                  name="3DGeom-14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-14'].geometry}
                  material={materials[' dark brown']}
                />
              </group>
              <group
                position={[214.291, 1362.638, 63.74]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.364, 1]}>
                <mesh
                  name="3DGeom-11_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-11_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-12_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[214.291, 1075.236, 63.74]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.318, 1]}>
                <mesh
                  name="3DGeom-11_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-11_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-12_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[214.291, 905.945, 63.74]}
                rotation={[0, 0, -Math.PI]}
                scale={[1, 1.364, 1]}>
                <mesh
                  name="3DGeom-11_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-11_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-12_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[214.291, 256.339, 63.74]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-11_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-11_4'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-12_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12_4'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[214.291, 390.197, 63.74]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-11_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-11_5'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-12_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12_5'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[228.071, 148.071, 63.74]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[1, 0.727, 1]}>
                <mesh
                  name="3DGeom-11_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-11_6'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-12_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12_6'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[558.78, 1098.858, 90.354]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.111, 1, 1]}>
                <mesh
                  name="3DGeom-27"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-28"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[558.78, 713.031, 111.732]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[1.111, 1, 1]}>
                <mesh
                  name="3DGeom-27_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-28_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[432.992, 205.157, 98.228]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.678, 1, 1]}>
                <mesh
                  name="3DGeom-27_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-28_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[519.213, 205.157, 98.228]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.678, 1, 1]}>
                <mesh
                  name="3DGeom-27_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-28_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[352.087, 1390.197, 99.921]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-27_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_4'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-28_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28_4'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[241.85, 1390.197, 93.74]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={[0.667, 1, 1]}>
                <mesh
                  name="3DGeom-37"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-38"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[277.283, 1390.197, 93.74]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={[0.667, 1, 1]}>
                <mesh
                  name="3DGeom-37_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-38_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[558.78, 634.291, 93.74]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[0.833, 1, 1]}>
                <mesh
                  name="3DGeom-37_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-38_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[558.78, 309.488, 93.74]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-37_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-38_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[468.78, 1098.858, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-45"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[241.575, 1216.969, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-45_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[306.811, 1000.157, 15.748]}>
                <mesh
                  name="3DGeom-45_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[306.811, 828.898, 15.748]}>
                <mesh
                  name="3DGeom-45_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[312.047, 328.898, 15.748]}>
                <mesh
                  name="3DGeom-45_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_4'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_4'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[393.425, 291.496, 15.748]}>
                <mesh
                  name="3DGeom-45_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_5'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_5'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[393.425, 616.299, 15.748]}>
                <mesh
                  name="3DGeom-45_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_6'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_6'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[216.26, 521.811, 15.748]}>
                <mesh
                  name="3DGeom-45_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_7'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_7'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[216.26, 443.071, 15.748]}>
                <mesh
                  name="3DGeom-45_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_8'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_8'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[306.811, 635.984, 15.748]}>
                <mesh
                  name="3DGeom-45_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-45_9'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-46_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-46_9'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[153.268, 541.772, 111.732]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-27_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_5'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-28_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28_5'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[153.268, 459.094, 111.732]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-27_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_6'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-28_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28_6'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[-259.745, 525.943, 0.39]}>
                <mesh
                  name="3DGeom-69"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-69'].geometry}
                  material={materials['[0100_SteelBlue]']}
                />
              </group>
              <group position={[506.209, 272.622, 15.748]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-70"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-70'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-71"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-71'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[514.838, 647.325, 15.748]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-70_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-70_1'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-71_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-71_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[441.381, 560.462, 15.748]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-70_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-70_2'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-71_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-71_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[236.652, 401.211, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-70_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-70_3'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-71_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-71_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[448.424, 447.821, 15.748]}>
                <mesh
                  name="3DGeom-70_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-70_4'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-71_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-71_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[491.019, 453.415, 15.746]} rotation={[0, 0, Math.PI]} scale={0.1}>
                <mesh
                  name="3DGeom-80"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-80'].geometry}
                  material={materials['[0045_Goldenrod]']}
                />
              </group>
              <group position={[391.151, 554.689, 22.19]} scale={0.1}>
                <mesh
                  name="3DGeom-80_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-80_1'].geometry}
                  material={materials['[0045_Goldenrod]']}
                />
              </group>
              <group position={[522.691, 676.487, 15.748]} scale={0.1}>
                <mesh
                  name="3DGeom-80_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-80_2'].geometry}
                  material={materials['[0045_Goldenrod]']}
                />
              </group>
              <group
                position={[314.522, 541.081, 15.544]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.1}>
                <mesh
                  name="3DGeom-80_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-80_3'].geometry}
                  material={materials['[0045_Goldenrod]']}
                />
              </group>
            </group>
             )}
              {visibleFloors.includes('roof') && (
            <group name="roof" position={[-5496.064, -15677.852, 4058]} scale={25.4}>
              <mesh
                name="3DGeom-84"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-84'].geometry}
                material={materials['[0117_GhostWhite]']}
              />
              <mesh
                name="3DGeom-85"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-85'].geometry}
                material={materials['[0117_GhostWhite]']}
              />
              <mesh
                name="3DGeom-86"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-86'].geometry}
                material={materials['[0074_SeaGreen]']}
              />
              <group position={[-1.392, -1.676, 15.748]}>
                <mesh
                  name="3DGeom-87"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-87'].geometry}
                  material={materials['[0074_SeaGreen]']}
                />
                <mesh
                  name="3DGeom-88"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-88'].geometry}
                  material={materials['[0074_SeaGreen]']}
                />
              </group>
            </group>
              )}
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Infirmary.glb')
