/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}
export function MSM({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props) {
  const { nodes, materials } = useGLTF('/MSM.glb') as any;
  return (
    <group  {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[-156,0,222]} rotation={[0, -Math.PI / 7.5, 0, ]} >
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-74" scale={0.001}>
            <group
              name="Active_View"
              position={[70825.867, 17669.314, 40616.023]}
              rotation={[-0.22, 0.953, 1.839]}
              scale={1000}
            />
              {visibleFloors.includes('1ST') && (
            <group name="MSM" position={[-15587.965, -15909.988, 0]} scale={25.4}>
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials['[0091_MintCream]']}
              />
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials['[0096_SkyBlue]']}
              />
              <mesh
                name="3DGeom-4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-4'].geometry}
                material={materials.tiless}
              />
              <mesh
                name="3DGeom-5"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-5'].geometry}
                material={materials['[Wood Veneer 01]']}
              />
              <mesh
                name="3DGeom-6"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-6'].geometry}
                material={materials['[0135_DarkGray]']}
              />
              <mesh
                name="3DGeom-7"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-7'].geometry}
                material={materials['[Translucent Glass Gray]1']}
              />
              <group position={[1110.236, 330.709, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[866.142, 330.709, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_1'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[622.047, 330.709, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_2'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[456.693, 330.709, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_3'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[353.268, 415.354, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_4'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_4'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[944.882, 415.354, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_5'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_5'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[523.622, 415.354, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_6'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_6'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[1110.236, 982.283, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_7'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_7'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[866.142, 982.283, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_8'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_8'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[622.047, 982.283, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_9'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_9'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[456.693, 982.283, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_10'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_10'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[944.882, 897.638, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_11'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_11'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[523.622, 897.638, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_12'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_12'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group
                position={[173.228, 389.764, 59.055]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-8_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_13'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_13'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group
                position={[173.228, 520.748, 59.055]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-8_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_14'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_14'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group
                position={[173.228, 786.339, 59.055]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-8_15"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_15'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_15"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_15'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group
                position={[173.228, 917.323, 59.055]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-8_16"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_16'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_16"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_16'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group
                position={[173.228, 1181.102, 59.055]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-8_17"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_17'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_17"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_17'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group
                position={[173.228, 125.984, 59.055]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-8_18"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_18'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_18"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_18'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group position={[284.528, 659.449, 59.055]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-8_19"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_19'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_19"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_19'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group
                position={[257.874, 865.079, 59.055]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-8_20"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_20'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
                <mesh
                  name="3DGeom-9_20"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_20'].geometry}
                  material={materials['[0042_Sienna]']}
                />
              </group>
              <group
                position={[1232.283, 1062.992, 90.551]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-50"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-50'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-51"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-51'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[1234.252, 1062.992, 90.551]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-50_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-50_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-51_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-51_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[1234.252, 1220.472, 90.551]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-50_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-50_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-51_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-51_2'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[1234.252, 244.094, 90.551]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-50_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-50_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-51_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-51_3'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[1234.252, 86.614, 90.551]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-50_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-50_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-51_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-51_4'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[866.268, 1.969, 90.551]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-60"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-60'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-61"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-61'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[1110.236, 1.969, 90.551]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-60_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-60_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-61_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-61_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[622.047, 1.969, 90.551]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-60_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-60_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-61_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-61_2'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[377.953, 1.969, 90.551]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-60_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-60_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-61_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-61_3'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[757.029, 1257.184, 15.748]}>
                <mesh
                  name="3DGeom-68"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68'].geometry}
                  material={materials['[0096_SkyBlue]']}
                />
              </group>
              <group position={[1002.62, 1257.184, 15.748]}>
                <mesh
                  name="3DGeom-68_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_1'].geometry}
                  material={materials['[0096_SkyBlue]']}
                />
              </group>
              <group position={[514.195, 1257.184, 15.748]}>
                <mesh
                  name="3DGeom-68_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_2'].geometry}
                  material={materials['[0096_SkyBlue]']}
                />
              </group>
              <group position={[1218.379, 51.331, 15.748]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-68_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_3'].geometry}
                  material={materials['[0096_SkyBlue]']}
                />
              </group>
              <group position={[973.97, 51.331, 15.748]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-68_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_4'].geometry}
                  material={materials['[0096_SkyBlue]']}
                />
              </group>
              <group position={[728.419, 51.331, 15.748]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-68_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-68_5'].geometry}
                  material={materials['[0096_SkyBlue]']}
                />
              </group>
              <group position={[92.015, 302.837, 15.748]}>
                <mesh
                  name="3DGeom-74"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-74'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-75"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-75'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[153.635, 449.243, 15.748]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-74_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-74_1'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-75_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-75_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[1218.933, 802.068, 15.748]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-74_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-74_2'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-75_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-75_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[369.028, 604.666, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-74_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-74_3'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-75_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-75_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[12.404, 211.006, 15.748]}>
                <mesh
                  name="3DGeom-74_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-74_4'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-75_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-75_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[1175.289, 794.824, 15.748]} scale={0.132}>
                <mesh
                  name="3DGeom-84"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[140.219, 303.968, 15.748]}
                rotation={[0, 0, -Math.PI]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_1'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group position={[63.447, 212.123, 15.748]} rotation={[0, 0, -Math.PI]} scale={0.132}>
                <mesh
                  name="3DGeom-84_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_2'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group position={[108.991, 448.137, 15.748]} scale={0.132}>
                <mesh
                  name="3DGeom-84_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_3'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[879.497, 555.637, 15.478]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_4'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[879.497, 593.669, 15.478]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_5'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[881.823, 623.478, 15.748]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_6'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[881.823, 656.627, 15.748]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_7'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[881.823, 691.037, 15.748]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_8'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[832.096, 593.669, 15.478]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_9'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[834.422, 623.478, 15.748]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_10'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[834.422, 691.037, 15.748]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_11'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[834.422, 656.627, 15.748]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_12'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[832.096, 555.637, 15.478]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_13'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[776.616, 543.69, 15.748]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_14'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[776.616, 581.722, 15.748]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_15"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_15'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[778.942, 679.09, 16.018]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_16"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_16'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[778.942, 644.681, 16.018]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_17"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_17'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group
                position={[778.942, 611.531, 16.018]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={0.132}>
                <mesh
                  name="3DGeom-84_18"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-84_18'].geometry}
                  material={materials['[Color D01]']}
                />
              </group>
              <group position={[1230.315, 574.803, 15.748]}>
                <mesh
                  name="3DGeom-103"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-103'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <group position={[0.984, 1.969, 0]}>
                  <mesh
                    name="3DGeom-104"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-104'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                  <group position={[-1583.11, -29.567, 1988.526]} rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="3DGeom-105"
                      castShadow
                      receiveShadow
                      geometry={nodes['3DGeom-105'].geometry}
                      material={materials['[0132_LightGray]']}
                    />
                  </group>
                </group>
              </group>
              <group position={[1230.315, 692.913, 15.748]}>
                <mesh
                  name="3DGeom-106"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-106'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <group position={[0.984, 1.969, 0]}>
                  <mesh
                    name="3DGeom-107"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-107'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                  <group position={[-1583.11, -55.472, 1988.526]} rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="3DGeom-108"
                      castShadow
                      receiveShadow
                      geometry={nodes['3DGeom-108'].geometry}
                      material={materials['[0132_LightGray]']}
                    />
                  </group>
                </group>
              </group>
              <group position={[-558.315, -1728.644, 0.976]}>
                <mesh
                  name="3DGeom-109"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-109'].geometry}
                  material={materials['[0100_SteelBlue]']}
                />
              </group>
              <group position={[-161.897, -776.839, 0.377]}>
                <mesh
                  name="3DGeom-110"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-110'].geometry}
                  material={materials['[0100_SteelBlue]']}
                />
              </group>
              <group position={[-558.388, -1256.123, 0.781]}>
                <mesh
                  name="3DGeom-111"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-111'].geometry}
                  material={materials['[0100_SteelBlue]']}
                />
              </group>
              <group position={[-161.897, -491.17, 1.479]}>
                <mesh
                  name="3DGeom-112"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-112'].geometry}
                  material={materials['[0100_SteelBlue]']}
                />
              </group>
            </group>
              )}
                {visibleFloors.includes('roof') && (
            <group name="roof" position={[-16587.965, -16909.988, 3600]} scale={25.4}>
              <mesh
                name="3DGeom-113"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-113'].geometry}
                material={materials['[0074_SeaGreen]']}
              />
              <mesh
                name="3DGeom-114"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-114'].geometry}
                material={materials['[0052_FloralWhite]']}
              />
              <group position={[-1.043, -1.144, 15.748]}>
                <mesh
                  name="3DGeom-115"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-115'].geometry}
                  material={materials['[0074_SeaGreen]']}
                />
              </group>
            </group>
             )}
            <mesh
              name="3DGeom-1"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-1'].geometry}
              material={nodes['3DGeom-1'].material}
              scale={25.4}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/MSM.glb')
