/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}
export function NewGirlsdorm({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props)  {
  const { nodes, materials } = useGLTF('/new girls dormitory.glb') as any;
  return (
    <group  {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[100,0,-213]}  rotation={[0, -Math.PI /1.6 , 0, ]}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-55" scale={0.001}>
            <group
              name="Active_View"
              position={[75967.711, -3085.617, 53573.57]}
              rotation={[-0.053, 0.966, 1.635]}
              scale={1000}
            />
             {visibleFloors.includes('2ND') && (
            <group name="2nd" position={[-7193.837, -15404.004, 3500]} scale={25.4}>
              <mesh
                name="3DGeom-1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-1'].geometry}
                material={materials['[0052_FloralWhite]']}
              />
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials['[0034_Wheat]']}
              />
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials.floor}
              />
              <mesh
                name="3DGeom-4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-4'].geometry}
                material={materials['[0042_Sienna]1']}
              />
              <group position={[7.874, 1041.339, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 887.795, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 561.024, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 407.48, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 253.937, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_4'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[547.244, 305.118, 55.669]}>
                <mesh
                  name="3DGeom-5_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_5'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[547.244, 458.661, 55.669]}>
                <mesh
                  name="3DGeom-5_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_6'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[547.244, 785.433, 55.669]}>
                <mesh
                  name="3DGeom-5_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_7'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[547.244, 938.976, 55.669]}>
                <mesh
                  name="3DGeom-5_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_8'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_8'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[549.213, 673.228, 69.173]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-23"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-23'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-24"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-24'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[220.472, 185.039, 19.685]}>
                <mesh
                  name="3DGeom-25"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 338.583, 19.685]}>
                <mesh
                  name="3DGeom-25_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_1'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 492.126, 19.685]}>
                <mesh
                  name="3DGeom-25_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_2'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 818.898, 19.685]}>
                <mesh
                  name="3DGeom-25_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_3'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 972.441, 19.685]}>
                <mesh
                  name="3DGeom-25_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_4'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 1125.984, 19.685]}>
                <mesh
                  name="3DGeom-25_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_5'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[330.709, 1125.984, 19.685]}>
                <mesh
                  name="3DGeom-25_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_6'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[330.709, 972.441, 19.685]}>
                <mesh
                  name="3DGeom-25_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_7'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[330.709, 818.898, 19.685]}>
                <mesh
                  name="3DGeom-25_8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_8'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[330.709, 492.126, 19.685]}>
                <mesh
                  name="3DGeom-25_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_9'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[330.709, 338.583, 19.685]}>
                <mesh
                  name="3DGeom-25_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_10'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[326.772, 185.039, 19.685]}>
                <mesh
                  name="3DGeom-25_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_11'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[440.945, 122.047, 106.85]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-37"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-38"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
            </group>
             )}
             {visibleFloors.includes('roof') && (

            <group name="roof" position={[-8193.837, -12986.556, 7000]} scale={25.4}>
              <mesh
                name="3DGeom-39"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-39'].geometry}
                material={nodes['3DGeom-39'].material}
              />
              <mesh
                name="3DGeom-40"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-40'].geometry}
                material={materials['[0034_Wheat]']}
              />
              <mesh
                name="3DGeom-41"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-41'].geometry}
                material={materials['[0100_SteelBlue]']}
              />
              <mesh
                name="3DGeom-42"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-42'].geometry}
                material={materials['[0042_Sienna]1']}
              />
              <group name="m" position={[-783.028, -1605.923, -275.591]}>
                <mesh
                  name="3DGeom-43"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-43'].geometry}
                  material={materials['[0100_SteelBlue]']}
                />
              </group>
              <group name="m_1" position={[-783.028, -1605.923, -275.591]}>
                <mesh
                  name="3DGeom-44"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-44'].geometry}
                  material={materials['[0100_SteelBlue]']}
                />
              </group>
            </group>
             )}
               {visibleFloors.includes('1ST') && (

            <group name="1st" position={[-7193.837, -15404.004, 0]} scale={25.4}>
              <mesh
                name="3DGeom-45"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-45'].geometry}
                material={materials.floor}
              />
              <mesh
                name="3DGeom-46"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-46'].geometry}
                material={materials['[0052_FloralWhite]']}
              />
              <mesh
                name="3DGeom-47"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-47'].geometry}
                material={materials['[0042_Sienna]1']}
              />
              <mesh
                name="3DGeom-48"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-48'].geometry}
                material={materials['[0034_Wheat]']}
              />
              <mesh
                name="3DGeom-49"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-49'].geometry}
                material={materials.tiless}
              />
              <mesh
                name="3DGeom-50"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-50'].geometry}
                material={materials['[0133_Gray]']}
              />
              <group position={[551.181, 305.118, 55.669]}>
                <mesh
                  name="3DGeom-5_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_9'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_9'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[547.244, 458.661, 55.669]}>
                <mesh
                  name="3DGeom-5_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_10'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_10'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[551.181, 785.433, 55.669]}>
                <mesh
                  name="3DGeom-5_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_11'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_11'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[551.181, 938.976, 55.669]}>
                <mesh
                  name="3DGeom-5_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_12'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_12'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 253.937, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_13'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_13'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 407.48, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_14'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_14'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 561.024, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_15"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_15'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_15"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_15'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 887.795, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_16"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_16'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_16"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_16'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[7.874, 1041.339, 55.669]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-5_17"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5_17'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6_17"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6_17'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[220.472, 1125.984, 19.685]}>
                <mesh
                  name="3DGeom-25_12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_12'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 972.441, 19.685]}>
                <mesh
                  name="3DGeom-25_13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_13'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 818.898, 19.685]}>
                <mesh
                  name="3DGeom-25_14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_14'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 655.512, 19.685]}>
                <mesh
                  name="3DGeom-25_15"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_15'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 492.126, 19.685]}>
                <mesh
                  name="3DGeom-25_16"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_16'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 338.583, 19.685]}>
                <mesh
                  name="3DGeom-25_17"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_17'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[220.472, 185.039, 19.685]}>
                <mesh
                  name="3DGeom-25_18"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_18'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[334.646, 185.039, 19.685]}>
                <mesh
                  name="3DGeom-25_19"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_19'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[334.646, 338.583, 19.685]}>
                <mesh
                  name="3DGeom-25_20"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_20'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[334.646, 492.126, 19.685]}>
                <mesh
                  name="3DGeom-25_21"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_21'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[334.646, 818.898, 19.685]}>
                <mesh
                  name="3DGeom-25_22"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_22'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[334.646, 972.441, 19.685]}>
                <mesh
                  name="3DGeom-25_23"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_23'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[334.646, 1125.984, 19.685]}>
                <mesh
                  name="3DGeom-25_24"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25_24'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[549.213, 673.228, 69.173]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-82"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-82'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-83"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-83'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[440.945, 122.047, 106.85]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-37_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-38_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[440.945, 1220.472, 106.85]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-86"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-86'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-87"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-87'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[389.921, 966.979, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-88"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-88'].geometry}
                  material={materials['[Tile Various Tan]']}
                />
                <mesh
                  name="3DGeom-89"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-89'].geometry}
                  material={materials['[Terrazzo Tile Light]']}
                />
              </group>
            </group>
              )}
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/new girls dormitory.glb')
