/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Park() {
  const { nodes, materials } = useGLTF('/park.glb') as any;
  return (
    <group dispose={null} position={[-98,0,90]} rotation={[0, -Math.PI / 1.56, 0, ]} scale={[0.9,1,0.9]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.001}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['3DGeom-1'].geometry}
            material={nodes['3DGeom-1'].material}
            scale={25.4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['3DGeom-2'].geometry}
            material={materials['[0062_YellowGreen]']}
            scale={25.4}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/park.glb')
