/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}

export function PHYSICALPLANT({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props) {
  const { nodes, materials } = useGLTF('/physical plant.glb') as any;
  return (
    <group {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[59,0,-225]}  rotation={[0, -Math.PI /1.6 , 0, ]} scale={[1.2,1.2,1.2]}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-22" scale={0.001}>
            <group
              name="Active_View"
              position={[43612.621, 10936.495, 34825.227]}
              rotation={[-0.254, 0.836, 1.907]}
              scale={1000}
            />
              {visibleFloors.includes('1ST') && (
            <group name="1st" position={[-4165.319, -6729.154, 0]} scale={25.4}>
              <mesh
                name="3DGeom-1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-1'].geometry}
                material={materials['[0034_Wheat]']}
              />
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials['[Polished Concrete Old]']}
              />
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials['[0023_FireBrick]']}
              />
              <mesh
                name="3DGeom-4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-4'].geometry}
                material={materials['[White Square Tile]']}
              />
              <mesh
                name="3DGeom-5"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-5'].geometry}
                material={materials['[Asphalt New]']}
              />
              <group position={[297.48, 275.827, 68.898]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[295.906, 358.504, 59.606]}>
                <mesh
                  name="3DGeom-8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-10"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[281.732, 514.409, 59.606]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1, 0.722, 1]}>
                <mesh
                  name="3DGeom-8_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-9_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_1'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-10_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[147.874, 514.409, 59.606]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1, 0.722, 1]}>
                <mesh
                  name="3DGeom-8_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-9_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_2'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-10_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[179.37, 37.244, 59.606]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[1, 0.722, 1]}>
                <mesh
                  name="3DGeom-8_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-9_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_3'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-10_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_3'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[295.906, 51.417, 59.606]}>
                <mesh
                  name="3DGeom-8_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-9_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_4'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-10_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_4'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group
                position={[45.512, 37.244, 59.606]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[1, 0.722, 1]}>
                <mesh
                  name="3DGeom-8_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-9_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_5'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-10_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-10_5'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[96.693, 212.835, 82.677]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-26"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-26'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-27"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27'].geometry}
                  material={materials['[Translucent Glass Gray]1']}
                />
              </group>
              <group position={[230.551, 212.835, 82.677]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-26_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-26_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-27_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_1'].geometry}
                  material={materials['[Translucent Glass Gray]1']}
                />
              </group>
              <group position={[167.559, 429.37, 82.677]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-30"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-30'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-31"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-31'].geometry}
                  material={materials['[Translucent Glass Gray]1']}
                />
              </group>
              <group position={[161.85, 74.911, 23.622]}>
                <mesh
                  name="3DGeom-32"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-32'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-33"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33'].geometry}
                  material={materials['[Carpet Loop Pattern]']}
                />
              </group>
              <group position={[32.165, 71.525, 23.622]}>
                <mesh
                  name="3DGeom-32_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-32_1'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-33_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_1'].geometry}
                  material={materials['[Carpet Loop Pattern]']}
                />
              </group>
              <group position={[127.728, 454.399, 23.622]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-32_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-32_2'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-33_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_2'].geometry}
                  material={materials['[Carpet Loop Pattern]']}
                />
              </group>
              <group position={[68.515, 333.77, 23.622]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-32_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-32_3'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-33_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-33_3'].geometry}
                  material={materials['[Carpet Loop Pattern]']}
                />
              </group>
              <group name="ergonomic_chair" position={[45.451, 286.331, 23.622]}>
                <mesh
                  name="3DGeom-40"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-41"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-41'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group
                name="ergonomic_chair_1"
                position={[220.325, 77.959, 23.622]}
                rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-40_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-41_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-41_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group name="ergonomic_chair_2" position={[80.055, 444.743, 23.622]}>
                <mesh
                  name="3DGeom-40_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-41_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-41_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group
                name="ergonomic_chair_3"
                position={[79.774, 77.959, 23.622]}
                rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-40_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-40_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-41_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-41_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
            </group>
              )}
               {visibleFloors.includes('roof') && (
            <group name="roof" position={[-4309.319, -6723.154, 3600]} scale={25.4}>
              <mesh
                name="3DGeom-48"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-48'].geometry}
                material={materials['[0052_FloralWhite]']}
              />
              <mesh
                name="3DGeom-49"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-49'].geometry}
                material={materials['[0068_LightGreen]']}
              />
              <group position={[-0.648, -0.88, 15.748]}>
                <mesh
                  name="3DGeom-50"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-50'].geometry}
                  material={materials['[0068_LightGreen]']}
                />
              </group>
            </group>
               )}
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/physical plant.glb')
