/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}
export function ROTC({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props){
  const { nodes, materials } = useGLTF('/ROTC.glb') as any;
  return (
    <group  {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null}  position={[-169,0,86]}  rotation={[0,-Math.PI / 8, 0, ]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group name="Assembly-28" scale={0.001}>
            {visibleFloors.includes('roof') && (
          <group name="roof" position={[-850, -910.871, 4144.876]} scale={25.4}>
            <group position={[0, 209.089, 17.918]}>
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials['[0129_WhiteSmoke]']}
              />
              <mesh
                name="3DGeom-4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-4'].geometry}
                material={materials.magenta}
              />
            </group>
            <mesh
              name="3DGeom-1"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-1'].geometry}
              material={materials.magenta}
            />
            <mesh
              name="3DGeom-2"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-2'].geometry}
              material={materials['[0129_WhiteSmoke]']}
            />
          </group>
            )}
              {visibleFloors.includes('1ST') && (
          <group name="1st" scale={25.4}>
            <mesh
              name="3DGeom-5"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-5'].geometry}
              material={materials['crea,']}
            />
            <mesh
              name="3DGeom-6"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-6'].geometry}
              material={materials.magenta}
            />
            <mesh
              name="3DGeom-7"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-7'].geometry}
              material={materials['[Polished Concrete Old]']}
            />
            <mesh
              name="3DGeom-8"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-8'].geometry}
              material={materials['[White Square Tile]']}
            />
            <mesh
              name="3DGeom-9"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-9'].geometry}
              material={materials['[0129_WhiteSmoke]']}
            />
            <mesh
              name="3DGeom-10"
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-10'].geometry}
              material={materials['crea,']}
            />
            <group position={[31.496, 0, 11.811]}>
              <group position={[212.598, 285.984, 75.354]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-11"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-11'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-12"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-12'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[147.638, 3.937, 65.512]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-13'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-14'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[212.598, 411.969, 75.354]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-15"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-15'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-16"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-16'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[9.843, 3.937, 85.197]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-17"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-17'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-18"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-18'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[246.063, 3.937, 65.512]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="3DGeom-13_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-13_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-14_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-14_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[212.598, 248.583, 75.354]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-21"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-21'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-22"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-22'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[92.52, 468.504, 75.354]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-23"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-23'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-24"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-24'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[303.15, 86.614, 65.512]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-25"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-25'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-26"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-26'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[212.598, 203.031, 47.52]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-27"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-28"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[212.598, 348.701, 47.52]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-27_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-28_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28_1'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[242.402, 169.291, 47.52]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-27_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-27_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-28_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-28_2'].geometry}
                  material={materials['[Translucent Glass Gray]']}
                />
              </group>
              <group position={[257.266, 384.18, 0]}>
                <mesh
                  name="3DGeom-34"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-34'].geometry}
                  material={materials['[Wood Veneer 01]']}
                />
                <mesh
                  name="3DGeom-35"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35'].geometry}
                  material={materials['[0004_HotPink]']}
                />
                <mesh
                  name="3DGeom-36"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-36'].geometry}
                  material={materials['crea,']}
                />
              </group>
              <group position={[19.66, 270.353, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-38"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-39"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[119.419, 90.681, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-38_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_1'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-39_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[44.764, 440.36, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-38_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-38_2'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-39_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-39_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <mesh
                name="3DGeom-31"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-31'].geometry}
                material={materials['[0043_SaddleBrown]']}
                position={[47.244, 120.433, 0]}
                scale={[1, 1, 0.87]}
              />
              <mesh
                name="3DGeom-37"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-37'].geometry}
                material={materials['[0047_Khaki]']}
                position={[303.958, 195.479, 0]}
                rotation={[0, 0, Math.PI]}
                scale={0.1}
              />
              <mesh
                name="3DGeom-40"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-40'].geometry}
                material={materials['[0129_WhiteSmoke]']}
                position={[275.591, 265.982, 0]}
              />
              <mesh
                name="3DGeom-37_1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-37_1'].geometry}
                material={materials['[0047_Khaki]']}
                position={[38.982, 395.469, 0]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.1}
              />
              <mesh
                name="3DGeom-37_2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-37_2'].geometry}
                material={materials['[0047_Khaki]']}
                position={[236.812, 260.777, 0]}
                rotation={[0, 0, Math.PI]}
                scale={0.1}
              />
              <mesh
                name="3DGeom-37_3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-37_3'].geometry}
                material={materials['[0047_Khaki]']}
                position={[19.947, 229.827, 0]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.1}
              />
              <mesh
                name="3DGeom-37_4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-37_4'].geometry}
                material={materials['[0047_Khaki]']}
                position={[115.296, 43.075, 0]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.1}
              />
            </group>
          </group>
              )}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ROTC.glb')
