/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}
export function SEARCDEC({ visibleFloors = ["1ST", "2ND",'3RD', "roof"], selected, onSelect, onClick, ...props }: Props)  {
  const { nodes, materials } = useGLTF('/Seardec.glb') as any;
  return (
    <group {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[-134,0,134]} rotation={[0,  1.150, 0, ]} scale={[1.2,1.2,1.2]} >
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-85" scale={0.001}>
            <group
              name="Active_View"
              position={[41753.352, 22046.736, 6729.77]}
              rotation={[-1.623, 1.108, -3.095]}
              scale={1000}
            />
              {visibleFloors.includes('2ND') && (
            <group name="2nd" position={[900, 1000, 3500]} scale={25.4}>
              <mesh
                name="3DGeom-1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-1'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials['[Polished Concrete New]']}
              />
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-4"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-4'].geometry}
                material={materials['111']}
              />
              <mesh
                name="3DGeom-5"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-5'].geometry}
                material={materials['[White Square Tile]']}
              />
              <group name="2ndstairs" position={[489.528, 228.346, 7.874]}>
                <mesh
                  name="3DGeom-6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6'].geometry}
                  material={materials['[White Square Tile]']}
                />
              </group>
              <group name="2" position={[34.567, 0, 11.811]}>
                <group
                  position={[501.811, 619.193, 51.732]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={[0.91, 1, 1]}>
                  <mesh
                    name="3DGeom-7"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-7'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-8"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-8'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[440.079, 619.193, 51.732]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                  scale={[0.5, 1, 1]}>
                  <mesh
                    name="3DGeom-9"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-9'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-10"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-10'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[553.386, 496.948, 51.732]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  scale={[0.61, 1, 1]}>
                  <mesh
                    name="3DGeom-9_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-9_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-10_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-10_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[553.386, 564.074, 51.732]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-7_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-7_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-8_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-8_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[49.213, 619.193, 51.732]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-15"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-15'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-16"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-16'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[553.386, 330.709, 51.732]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-17"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-17'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-18"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-18'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[309.055, 619.193, 51.732]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-19"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-19'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-20"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-20'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[143.701, 619.193, 51.732]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-21"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-21'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-22"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-22'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[604.567, 114.173, 57.638]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-23"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-23'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-24"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-24'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[537.638, 3.937, 51.732]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-25"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-25'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-26"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-26'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[584.882, 275.591, 29.528]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  scale={[1, 1.5, 1]}>
                  <mesh
                    name="3DGeom-9_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-9_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-10_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-10_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[584.882, 275.591, 94.488]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-9_3"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-9_3'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-10_3"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-10_3'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[208.661, 619.193, 51.732]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-31"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-31'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-32"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-32'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[279.764, 3.937, 51.732]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[437.244, 3.937, 51.732]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[358.504, 3.937, 51.732]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[312.127, 451.71, 33.74]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-39"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group position={[288.071, 216.535, 33.74]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-39_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40_1'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group position={[218.74, 143.425, 33.74]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-39_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40_2'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
              </group>
              <group position={[4.331, 4.331, 7.874]}>
                <group name="Rail_TA" position={[0, 15.197, 0]}>
                  <mesh
                    name="3DGeom-45"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-45'].geometry}
                    material={materials['[0131_Silver]']}
                  />
                </group>
                <group name="Rail_TA_1" position={[15.748, 0, 0]}>
                  <mesh
                    name="3DGeom-46"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-46'].geometry}
                    material={materials['[0131_Silver]']}
                  />
                </group>
                <group name="Rail_TA_2" position={[190.315, 0, 0]}>
                  <mesh
                    name="3DGeom-47"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-47'].geometry}
                    material={materials['[0131_Silver]']}
                  />
                </group>
              </group>
            </group>
              )}
                {visibleFloors.includes('3RD') && (
            <group name="3rd" position={[900, 1000, 7000]} scale={25.4}>
              <mesh
                name="3DGeom-48"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-48'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-49"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-49'].geometry}
                material={materials['[Polished Concrete New]']}
              />
              <mesh
                name="3DGeom-50"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-50'].geometry}
                material={materials['111']}
              />
              <mesh
                name="3DGeom-51"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-51'].geometry}
                material={materials['[White Square Tile]']}
              />
              <mesh
                name="3DGeom-52"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-52'].geometry}
                material={materials['[0044_DarkGoldenrod]']}
              />
              <group name="3" position={[34.567, 31.496, 11.811]}>
                <group position={[498.268, 587.696, 13.78]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-53"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-53'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-54"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-54'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[553.386, 299.213, 51.732]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-17_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-17_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-18_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-18_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[604.567, 82.677, 57.638]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-23_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-23_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-24_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-24_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[553.386, 532.578, 13.78]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-53_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-53_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-54_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-54_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[584.882, 244.094, 49.213]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-61"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-61'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-62"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-62'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[437.913, 587.696, 13.78]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-63"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-63'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-64"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-64'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[208.661, 587.696, 23.622]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-31_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-31_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-32_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-32_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[553.386, 465.452, 13.78]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-63_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-63_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-64_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-64_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[49.213, 587.696, 23.622]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-15_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-15_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-16_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-16_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[143.701, 587.696, 23.622]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-21_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-21_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-22_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-22_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[309.055, 587.696, 23.622]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-19_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-19_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-20_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-20_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[537.638, -27.559, 51.732]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-25_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-25_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-26_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-26_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[279.764, -27.559, 51.732]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33_3"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33_3'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34_3"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34_3'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[437.244, -27.559, 51.732]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33_4"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33_4'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34_4"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34_4'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[358.504, -27.559, 51.732]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33_5"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33_5'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34_5"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34_5'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[301.26, 420.216, 33.74]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-39_3"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39_3'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40_3"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40_3'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group position={[286.89, 185.039, 33.74]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-39_4"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39_4'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40_4"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40_4'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group
                  position={[230.551, 111.89, 33.74]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-39_5"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39_5'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40_5"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40_5'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
              </group>
              <group position={[4.331, 4.331, 7.874]}>
                <group name="Rail_TA_3" position={[190.315, 0, 0]}>
                  <mesh
                    name="3DGeom-89"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-89'].geometry}
                    material={materials['[0131_Silver]']}
                  />
                </group>
                <group name="Rail_TA_4" position={[0, 15.748, 0]}>
                  <mesh
                    name="3DGeom-90"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-90'].geometry}
                    material={materials['[0131_Silver]']}
                  />
                </group>
                <group name="Rail_TA_5" position={[15.748, 0, 0]}>
                  <mesh
                    name="3DGeom-91"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-91'].geometry}
                    material={materials['[0131_Silver]']}
                  />
                </group>
              </group>
            </group>
             )}
                {visibleFloors.includes('1ST') && (
            <group name="1st" position={[900, 1000, 0]} scale={25.4}>
              <mesh
                name="3DGeom-92"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-92'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-93"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-93'].geometry}
                material={materials['[Polished Concrete New]']}
              />
              <mesh
                name="3DGeom-94"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-94'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-95"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-95'].geometry}
                material={materials['111']}
              />
              <mesh
                name="3DGeom-96"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-96'].geometry}
                material={materials['[White Square Tile]']}
              />
              <mesh
                name="3DGeom-97"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-97'].geometry}
                material={materials['[Concrete Scored Jointless]']}
              />
              <mesh
                name="3DGeom-98"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-98'].geometry}
                material={materials['[Blacktop Old 01]']}
              />
              <group name="1st_stairs" position={[489.528, 228.346, 7.874]}>
                <mesh
                  name="3DGeom-99"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-99'].geometry}
                  material={materials['[White Square Tile]']}
                />
              </group>
              <group name="1" position={[0, 0, 7.874]}>
                <group position={[450.197, 228.346, 37.677]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-39_6"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39_6'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40_6"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40_6'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group position={[249.686, 366.142, 37.677]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-39_7"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39_7'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40_7"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40_7'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group position={[178.268, 619.193, 55.669]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-21_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-21_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-22_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-22_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[572.205, 3.937, 55.669]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-25_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-25_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-26_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-26_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[3.937, 275.591, 61.575]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[1.051, 1, 1]}>
                  <mesh
                    name="3DGeom-108"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-108'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-109"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-109'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[365.866, 451.71, 37.677]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-39_8"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-39_8'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-40_8"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-40_8'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group position={[83.78, 619.193, 55.669]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-15_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-15_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-16_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-16_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[243.228, 619.193, 55.669]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-31_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-31_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-32_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-32_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[639.134, 114.173, 61.575]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-23_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-23_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-24_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-24_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[3.937, 535.451, 61.575]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-108_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-108_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-109_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-109_1'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[587.953, 564.074, 55.669]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-120"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-120'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-121"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-121'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[343.622, 619.193, 55.669]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-19_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-19_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-20_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-20_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[536.22, 619.193, 37.677]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-124"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-124'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-125"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-125'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group position={[448.504, 619.193, 37.677]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                  <mesh
                    name="3DGeom-124_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-124_1'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-125_1"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-125_1'].geometry}
                    material={materials['[Translucent Glass Gray]']}
                  />
                </group>
                <group position={[471.811, 3.937, 55.669]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33_6"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33_6'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34_6"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34_6'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[314.331, 3.937, 55.669]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33_7"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33_7'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34_7"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34_7'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[619.652, 275.591, 90.551]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-9_4"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-9_4'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-10_4"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-10_4'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[587.953, 496.948, 55.669]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-134"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-134'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-135"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-135'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[587.953, 330.709, 55.669]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                  <mesh
                    name="3DGeom-17_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-17_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-18_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-18_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group
                  position={[3.937, 90.551, 61.575]}
                  rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  scale={[1.051, 1, 1]}>
                  <mesh
                    name="3DGeom-108_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-108_2'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-109_2"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-109_2'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
                <group position={[393.071, 3.937, 55.669]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="3DGeom-33_8"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-33_8'].geometry}
                    material={materials['[0136_Charcoal]']}
                  />
                  <mesh
                    name="3DGeom-34_8"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-34_8'].geometry}
                    material={materials['[0135_DarkGray]']}
                  />
                </group>
              </group>
              <group name="Rail_TA_6" position={[398.573, 627.618, 7.874]}>
                <mesh
                  name="3DGeom-142"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-142'].geometry}
                  material={materials['*']}
                />
              </group>
            </group>
             )}
                {visibleFloors.includes('roof') && (
            <group name="roof" position={[900, 1000, 10312.095]} scale={25.4}>
              <mesh
                name="3DGeom-143"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-143'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-144"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-144'].geometry}
                material={materials['111']}
              />
              <mesh
                name="3DGeom-145"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-145'].geometry}
                material={materials.magenta}
              />
              <mesh
                name="3DGeom-146"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-146'].geometry}
                material={materials.cream}
              />
              <mesh
                name="3DGeom-147"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-147'].geometry}
                material={materials['[0044_DarkGoldenrod]']}
              />
              <group position={[0, 0, -12.287]}>
                <mesh
                  name="3DGeom-148"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-148'].geometry}
                  material={materials.cream}
                />
              </group>
              <group position={[46.694, -37.402, 78.74]}>
                <group position={[527.479, 326.772, 7.874]}>
                  <mesh
                    name="3DGeom-149"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-149'].geometry}
                    material={materials['111']}
                  />
                  <mesh
                    name="3DGeom-150"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-150'].geometry}
                    material={materials.cream}
                  />
                </group>
                <group position={[464.487, 0, 0]}>
                  <mesh
                    name="3DGeom-151"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-151'].geometry}
                    material={materials.cream}
                  />
                </group>
                <group position={[208.581, 0, 0]}>
                  <mesh
                    name="3DGeom-152"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-152'].geometry}
                    material={materials.cream}
                  />
                </group>
                <group position={[251.652, 644.783, 0]}>
                  <mesh
                    name="3DGeom-153"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-153'].geometry}
                    material={materials['111']}
                  />
                </group>
                <group position={[0, 644.783, 0]}>
                  <mesh
                    name="3DGeom-154"
                    castShadow
                    receiveShadow
                    geometry={nodes['3DGeom-154'].geometry}
                    material={materials['111']}
                  />
                </group>
              </group>
              <group name="scafholding" position={[-35.433, -39.37, -405.988]}>
                <mesh
                  name="3DGeom-155"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-155'].geometry}
                  material={materials.cream}
                />
                <mesh
                  name="3DGeom-156"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-156'].geometry}
                  material={materials['111']}
                />
              </group>
            </group>
                )}
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Seardec.glb')
