/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}
export function SED({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props) {
  const { nodes, materials } = useGLTF('/SED.glb') as any;
  return (
    <group {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[25,0,-130 ]} rotation={[0,Math.PI / 1.14, 0, ]} scale={[1,1.2,1.3]} >
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Assembly-28" scale={0.001}>
            <group
              name="Active_View"
              position={[28842.371, 2424.502, 25765.951]}
              rotation={[-0.093, 0.919, 1.687]}
              scale={1000}
            /> 
            {visibleFloors.includes('1ST') && (
            <group name="SED_FL1" position={[-5263.338, -6179.153, 0]} scale={25.4}>
              <mesh
                name="3DGeom-1"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-1'].geometry}
                material={materials.creame}
              />
              <mesh
                name="3DGeom-2"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-2'].geometry}
                material={materials['[0021_DarkRed]']}
              />
              <mesh
                name="3DGeom-3"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-3'].geometry}
                material={materials['[White Square Tile]']}
              />
              <group position={[147.953, 7.874, 51.732]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-4'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-6'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[3.937, 473.071, 51.732]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-9"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[331.339, 35.433, 51.732]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-7_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_1'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-9_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[232.913, 307.402, 80.984]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-13"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-13'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-14"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-14'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[195.197, 3.937, 51.732]}>
                <mesh
                  name="3DGeom-7_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_2'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-9_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_2'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[331.339, 368.425, 51.732]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  name="3DGeom-7_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_3'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-9_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_3'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group
                position={[3.937, 313.307, 51.732]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[1.129, 1, 1]}>
                <mesh
                  name="3DGeom-7_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_4'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_4'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-9_4"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_4'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[3.937, 140.079, 51.732]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-7_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_5'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_5'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-9_5"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_5'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[140.079, 504.567, 51.732]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-7_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_6'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_6'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-9_6"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_6'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[299.843, 504.567, 51.732]} rotation={[0, 0, -Math.PI]}>
                <mesh
                  name="3DGeom-7_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-7_7'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-8_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-8_7'].geometry}
                  material={materials['WB Glazing']}
                />
                <mesh
                  name="3DGeom-9_7"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-9_7'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[232.913, 201.102, 80.984]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                  name="3DGeom-13_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-13_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-14_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-14_1'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[232.913, 230.63, 15.748]}>
                <mesh
                  name="3DGeom-35"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-35'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
                <mesh
                  name="3DGeom-36"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-36'].geometry}
                  material={materials['[0135_DarkGray]']}
                />
              </group>
              <group position={[236.687, 37.32, 15.746]}>
                <mesh
                  name="3DGeom-37"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37'].geometry}
                  material={materials['[0056_Yellow]']}
                />
              </group>
              <group position={[23.628, 244.275, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-37_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37_1'].geometry}
                  material={materials['[0056_Yellow]']}
                />
              </group>
              <group position={[248.026, 474.783, 15.746]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-37_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37_2'].geometry}
                  material={materials['[0056_Yellow]']}
                />
              </group>
              <group position={[66.923, 37.32, 15.746]}>
                <mesh
                  name="3DGeom-37_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-37_3'].geometry}
                  material={materials['[0056_Yellow]']}
                />
              </group>
              <group position={[207.334, 61.512, 15.748]}>
                <mesh
                  name="3DGeom-41"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-41'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-42"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-42'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[276.005, 446.823, 15.748]} rotation={[0, 0, Math.PI]}>
                <mesh
                  name="3DGeom-41_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-41_1'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-42_1"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-42_1'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[52.834, 276.224, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                  name="3DGeom-41_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-41_2'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-42_2"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-42_2'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[38.267, 60.161, 15.748]}>
                <mesh
                  name="3DGeom-41_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-41_3'].geometry}
                  material={materials['[Wood Bamboo]']}
                />
                <mesh
                  name="3DGeom-42_3"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-42_3'].geometry}
                  material={materials['[0136_Charcoal]']}
                />
              </group>
              <group position={[-882.86, 507.412, 0]}>
                <mesh
                  name="3DGeom-49"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-49'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[-390.591, -649.877, 0]}>
                <mesh
                  name="3DGeom-50"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-50'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[-675.894, -283.39, 0]}>
                <mesh
                  name="3DGeom-51"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-51'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
              <group position={[-882.86, 159.46, 0]}>
                <mesh
                  name="3DGeom-52"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-52'].geometry}
                  material={materials['[0043_SaddleBrown]']}
                />
              </group>
            </group>
            )}
             {visibleFloors.includes('roof') && (
            <group name="SED_roof" position={[-6263.338, -7179.153, 3448]} scale={25.4}>
              <mesh
                name="3DGeom-53"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-53'].geometry}
                material={materials['[0117_GhostWhite]']}
              />
              <mesh
                name="3DGeom-54"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-54'].geometry}
                material={materials['[0117_GhostWhite]']}
              />
              <mesh
                name="3DGeom-55"
                castShadow
                receiveShadow
                geometry={nodes['3DGeom-55'].geometry}
                material={materials['[0021_DarkRed]']}
              />
              <group position={[-0.301, -0.386, 19.685]}>
                <mesh
                  name="3DGeom-56"
                  castShadow
                  receiveShadow
                  geometry={nodes['3DGeom-56'].geometry}
                  material={materials['[0021_DarkRed]']}
                />
              </group>
            </group>
             )}
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/SED.glb')
