// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// type Props = {
//   selected?: boolean
//   onSelect?: (id: string) => void
//   onClick?: () => void
//   visibleFloors?: string[]
// }
// export function SUPPLYANDPROCUREMENT({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props) {
//    const { nodes, materials } = useGLTF('/glb/supply and procurement office_compressed.glb') as any;
//   return (
//    <group  {...props}
//       onClick={(e) => {
//         e.stopPropagation()
//         onClick?.()
//       }}  dispose={null} position={[9,0,-58]} rotation={[0,-Math.PI / 15, 0, ]} scale={[1, 0.9, 1.2]}>
//       <group rotation={[-Math.PI / 2, 0, 0]}>
//         <group name="Assembly-148" scale={0.001}>
//              {visibleFloors.includes('1ST') && (
//           <group name="supply_and_procurement" position={[-8507.251, -14432.291, 0]} scale={25.4}>
//             <mesh
//               name="3DGeom-1"
//               castShadow
//               receiveShadow
//               geometry={nodes['3DGeom-1'].geometry}
//               material={materials['[0049_Beige]1']}
//               position={[270.472, 611.339, 84.449]}
//               scale={611.339}
//             />
//             <mesh
//               name="3DGeom-2"
//               castShadow
//               receiveShadow
//               geometry={nodes['3DGeom-2'].geometry}
//               material={materials['[White Square Tile]']}
//               position={[237.008, 611.457, 15.748]}
//               scale={599.409}
//             />
//             <mesh
//               name="3DGeom-3"
//               castShadow
//               receiveShadow
//               geometry={nodes['3DGeom-3'].geometry}
//               material={materials['[0022_Maroon]']}
//               position={[270.472, 611.339, 1.969]}
//               scale={611.339}
//             />
//             <mesh
//               name="3DGeom-4"
//               castShadow
//               receiveShadow
//               geometry={nodes['3DGeom-4'].geometry}
//               material={materials['*19']}
//               position={[5.906, 1114.409, 102.165]}
//               scale={96.457}
//             />
//             <group position={[98.756, 891.142, 15.748]}>
//               <mesh
//                 name="3DGeom-5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-5'].geometry}
//                 material={materials['*19']}
//                 position={[2, 17.992, 53.524]}
//                 scale={53.524}
//               />
//             </group>
//             <group position={[98.756, 828.15, 15.748]}>
//               <mesh
//                 name="3DGeom-5_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-5_1'].geometry}
//                 material={materials['*19']}
//                 position={[2, 17.992, 53.524]}
//                 scale={53.524}
//               />
//             </group>
//             <group position={[119.685, 722.638, 15.748]}>
//               <mesh
//                 name="3DGeom-7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-7'].geometry}
//                 material={materials['[0050_LemonChiffon]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={49.587}
//               />
//               <mesh
//                 name="3DGeom-8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-8'].geometry}
//                 material={materials['[0040_Peru]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={53.524}
//               />
//             </group>
//             <group position={[158.228, 220.772, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
//               <mesh
//                 name="3DGeom-5_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-5_2'].geometry}
//                 material={materials['*19']}
//                 position={[2, 17.992, 53.524]}
//                 scale={53.524}
//               />
//             </group>
//             <group position={[214.567, 1059.291, 15.748]}>
//               <mesh
//                 name="3DGeom-10"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-10'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[2.953, 75.787, 86.417]}
//                 scale={86.417}
//               />
//               <mesh
//                 name="3DGeom-11"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-11'].geometry}
//                 material={materials['[Translucent Glass Gray]']}
//                 position={[2.953, 75.787, 86.417]}
//                 scale={84.449}
//               />
//             </group>
//             <group position={[7.874, 924.252, 130.472]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-12"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-12'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[19.685, 19.685, 1.969]}
//                 scale={19.685}
//               />
//               <mesh
//                 name="3DGeom-13"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-13'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[19.685, 19.685, 2.165]}
//                 scale={17.717}
//               />
//             </group>
//             <group position={[7.874, 820.315, 130.472]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-12_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-12_1'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[19.685, 19.685, 1.969]}
//                 scale={19.685}
//               />
//               <mesh
//                 name="3DGeom-13_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-13_1'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[19.685, 19.685, 2.165]}
//                 scale={17.717}
//               />
//             </group>
//             <group position={[55.118, 1218.74, 63.74]} rotation={[Math.PI / 2, 0, 0]}>
//               <mesh
//                 name="3DGeom-16"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-16'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[39.37, 29.528, 1.969]}
//                 scale={39.37}
//               />
//               <mesh
//                 name="3DGeom-17"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-17'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[39.37, 29.528, 1.969]}
//                 scale={35.433}
//               />
//               <mesh
//                 name="3DGeom-18"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-18'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[39.37, 29.528, 2.362]}
//                 scale={35.433}
//               />
//             </group>
//             <group position={[115.748, 71.102, 51.732]}>
//               <mesh
//                 name="3DGeom-19"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-19'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[1.969, 47.244, 39.37]}
//                 scale={47.244}
//               />
//               <mesh
//                 name="3DGeom-20"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-20'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[1.969, 47.244, 39.37]}
//                 scale={43.307}
//               />
//               <mesh
//                 name="3DGeom-21"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-21'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[1.575, 47.244, 39.37]}
//                 scale={43.307}
//               />
//             </group>
//             <group position={[242.126, 1218.74, 63.74]} rotation={[Math.PI / 2, 0, 0]}>
//               <mesh
//                 name="3DGeom-16_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-16_1'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[39.37, 29.528, 1.969]}
//                 scale={39.37}
//               />
//               <mesh
//                 name="3DGeom-17_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-17_1'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[39.37, 29.528, 1.969]}
//                 scale={35.433}
//               />
//               <mesh
//                 name="3DGeom-18_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-18_1'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[39.37, 29.528, 2.362]}
//                 scale={35.433}
//               />
//             </group>
//             <group position={[7.874, 1088.031, 130.472]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-12_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-12_2'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[19.685, 19.685, 1.969]}
//                 scale={19.685}
//               />
//               <mesh
//                 name="3DGeom-13_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-13_2'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[19.685, 19.685, 2.165]}
//                 scale={17.717}
//               />
//             </group>
//             <group position={[139.37, 4.173, 51.732]}>
//               <mesh
//                 name="3DGeom-27"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-27'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[29.528, 1.969, 39.37]}
//                 scale={39.37}
//               />
//               <mesh
//                 name="3DGeom-28"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-28'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[29.528, 1.575, 39.37]}
//                 scale={35.433}
//               />
//               <mesh
//                 name="3DGeom-29"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-29'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[29.528, 1.969, 39.37]}
//                 scale={35.433}
//               />
//             </group>
//             <group position={[7.874, 713.622, 130.472]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-12_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-12_3'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[19.685, 19.685, 1.969]}
//                 scale={19.685}
//               />
//               <mesh
//                 name="3DGeom-13_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-13_3'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[19.685, 19.685, 2.165]}
//                 scale={17.717}
//               />
//             </group>
//             <group position={[7.874, 752.992, 130.472]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-12_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-12_4'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[19.685, 19.685, 1.969]}
//                 scale={19.685}
//               />
//               <mesh
//                 name="3DGeom-13_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-13_4'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[19.685, 19.685, 2.165]}
//                 scale={17.717}
//               />
//             </group>
//             <group position={[3.937, 1191.181, 51.732]} rotation={[0, 0, -Math.PI / 2]}>
//               <mesh
//                 name="3DGeom-27_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-27_1'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[29.528, 1.969, 39.37]}
//                 scale={39.37}
//               />
//               <mesh
//                 name="3DGeom-28_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-28_1'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[29.528, 1.575, 39.37]}
//                 scale={35.433}
//               />
//               <mesh
//                 name="3DGeom-29_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-29_1'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[29.528, 1.969, 39.37]}
//                 scale={35.433}
//               />
//             </group>
//             <group position={[358.268, 1096.693, 63.74]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-37"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-37'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[29.528, 29.528, 1.969]}
//                 scale={29.528}
//               />
//               <mesh
//                 name="3DGeom-38"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-38'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[29.528, 29.528, 1.969]}
//                 scale={25.591}
//               />
//               <mesh
//                 name="3DGeom-39"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-39'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[29.528, 29.528, 2.362]}
//                 scale={25.591}
//               />
//             </group>
//             <group position={[358.268, 1195.118, 63.74]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-37_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-37_1'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[29.528, 29.528, 1.969]}
//                 scale={29.528}
//               />
//               <mesh
//                 name="3DGeom-38_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-38_1'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[29.528, 29.528, 1.969]}
//                 scale={25.591}
//               />
//               <mesh
//                 name="3DGeom-39_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-39_1'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[29.528, 29.528, 2.362]}
//                 scale={25.591}
//               />
//             </group>
//             <group position={[279.134, 4.173, 51.732]}>
//               <mesh
//                 name="3DGeom-27_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-27_2'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[29.528, 1.969, 39.37]}
//                 scale={39.37}
//               />
//               <mesh
//                 name="3DGeom-28_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-28_2'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[29.528, 1.575, 39.37]}
//                 scale={35.433}
//               />
//               <mesh
//                 name="3DGeom-29_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-29_2'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[29.528, 1.969, 39.37]}
//                 scale={35.433}
//               />
//             </group>
//             <group position={[7.874, 859.685, 130.472]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-12_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-12_5'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[19.685, 19.685, 1.969]}
//                 scale={19.685}
//               />
//               <mesh
//                 name="3DGeom-13_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-13_5'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[19.685, 19.685, 2.165]}
//                 scale={17.717}
//               />
//             </group>
//             <group position={[358.268, 852.598, 63.74]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-48"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-48'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.417, 29.528, 1.969]}
//                 scale={36.417}
//               />
//               <mesh
//                 name="3DGeom-49"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-49'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[36.417, 29.528, 1.969]}
//                 scale={32.48}
//               />
//               <mesh
//                 name="3DGeom-50"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-50'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[36.417, 29.528, 2.362]}
//                 scale={32.48}
//               />
//             </group>
//             <group position={[470.079, 128.976, 63.74]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-51"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-51'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[39.37, 29.528, 1.969]}
//                 scale={39.37}
//               />
//               <mesh
//                 name="3DGeom-52"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-52'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[39.37, 29.528, 1.969]}
//                 scale={35.433}
//               />
//               <mesh
//                 name="3DGeom-53"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-53'].geometry}
//                 material={materials['WB Glazing']}
//                 position={[39.37, 29.528, 2.362]}
//                 scale={35.433}
//               />
//             </group>
//             <group position={[199.15, 302.126, 15.748]}>
//               <mesh
//                 name="3DGeom-5_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-5_3'].geometry}
//                 material={materials['*19']}
//                 position={[2, 17.992, 53.524]}
//                 scale={53.524}
//               />
//             </group>
//             <group position={[304.284, 1196.276, 15.748]} rotation={[0, 0, -3.14]}>
//               <mesh
//                 name="3DGeom-55"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[285.07, 39.1, 15.748]} rotation={[0, 0, -0.014]}>
//               <mesh
//                 name="3DGeom-55_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_1'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_1'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[131.906, 966.073, 15.748]} rotation={[0, 0, -1.555]}>
//               <mesh
//                 name="3DGeom-55_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_2'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_2'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[304.284, 1094.071, 15.748]} rotation={[0, 0, -3.14]}>
//               <mesh
//                 name="3DGeom-55_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_3'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_3'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[388.98, 141.485, 15.748]} rotation={[0, 0, -0.014]}>
//               <mesh
//                 name="3DGeom-55_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_4'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_4'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[135.919, 862.731, 15.748]} rotation={[0, 0, -1.553]}>
//               <mesh
//                 name="3DGeom-55_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_5'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_5'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[274.606, 805.189, 15.748]} rotation={[0, 0, -0.014]}>
//               <mesh
//                 name="3DGeom-55_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_6'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_6'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[198.268, 1182.405, 15.748]} rotation={[0, 0, -3.14]}>
//               <mesh
//                 name="3DGeom-55_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_7'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_7'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[190.775, 973.128, 15.748]} rotation={[0, 0, -1.555]}>
//               <mesh
//                 name="3DGeom-55_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_8'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_8'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[146.111, 37.249, 15.748]} rotation={[0, 0, -0.014]}>
//               <mesh
//                 name="3DGeom-55_9"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-55_9'].geometry}
//                 material={materials['[Wood Bamboo]']}
//                 position={[36.89, 22.323, 15]}
//                 scale={31.181}
//               />
//               <mesh
//                 name="3DGeom-56_9"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-56_9'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[36.89, 22.323, 30]}
//                 scale={31.181}
//               />
//             </group>
//             <group position={[333.604, 45.03, 15.748]} rotation={[0, 0, 3.025]}>
//               <mesh
//                 name="3DGeom-75"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group position={[433.963, 141.962, 15.748]} rotation={[0, 0, 3.025]}>
//               <mesh
//                 name="3DGeom-75_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75_1'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76_1'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77_1'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78_1'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79_1'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80_1'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81_1'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82_1'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83_1'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84_1"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84_1'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group position={[199.926, 39.094, 15.748]} rotation={[0, 0, 3.025]}>
//               <mesh
//                 name="3DGeom-75_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75_2'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76_2'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77_2'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78_2'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79_2'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80_2'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81_2'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82_2'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83_2'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84_2"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84_2'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group position={[243.588, 1090.766, 15.748]} rotation={[0, 0, 0.145]}>
//               <mesh
//                 name="3DGeom-75_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75_3'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76_3'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77_3'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78_3'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79_3'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80_3'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81_3'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82_3'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83_3'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84_3"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84_3'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group position={[308.374, 1163.55, 15.748]} rotation={[0, 0, 0.145]}>
//               <mesh
//                 name="3DGeom-75_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75_4'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76_4'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77_4'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78_4'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79_4'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80_4'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81_4'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82_4'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83_4'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84_4"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84_4'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group position={[192.982, 993.282, 15.748]} rotation={[0, 0, 3.025]}>
//               <mesh
//                 name="3DGeom-75_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75_5'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76_5'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77_5'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78_5'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79_5'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80_5'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81_5'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82_5'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83_5'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84_5"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84_5'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group position={[84.217, 1153.773, 15.748]} rotation={[0, 0, 0.145]}>
//               <mesh
//                 name="3DGeom-75_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75_6'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76_6'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77_6'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78_6'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79_6'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80_6'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81_6'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82_6'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83_6'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84_6"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84_6'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group position={[140.404, 833.44, 15.748]} rotation={[0, 0, 3.025]}>
//               <mesh
//                 name="3DGeom-75_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75_7'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76_7'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77_7'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78_7'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79_7'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80_7'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81_7'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82_7'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83_7'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84_7"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84_7'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group position={[320.981, 813.588, 15.748]} rotation={[0, 0, 3.025]}>
//               <mesh
//                 name="3DGeom-75_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-75_8'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.296, 5.824, 1.795]}
//                 scale={12.738}
//               />
//               <mesh
//                 name="3DGeom-76_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-76_8'].geometry}
//                 material={materials['[Color_008]2']}
//                 position={[13.289, 13.233, 1.412]}
//                 scale={13.229}
//               />
//               <mesh
//                 name="3DGeom-77_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-77_8'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.263, 15.174, 24.318]}
//                 scale={21.743}
//               />
//               <mesh
//                 name="3DGeom-78_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-78_8'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[13.305, 13.988, 12.204]}
//                 scale={2.232}
//               />
//               <mesh
//                 name="3DGeom-79_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-79_8'].geometry}
//                 material={materials.Mesh_Blue_540}
//                 position={[13.256, 16.358, 32.852]}
//                 scale={16.028}
//               />
//               <mesh
//                 name="3DGeom-80_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-80_8'].geometry}
//                 material={materials['[Color M00]']}
//                 position={[12.539, 18.848, 30.766]}
//                 scale={18.135}
//               />
//               <mesh
//                 name="3DGeom-81_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-81_8'].geometry}
//                 material={materials['[Color_003]']}
//                 position={[13.274, 14.007, 9.753]}
//                 scale={0.475}
//               />
//               <mesh
//                 name="3DGeom-82_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-82_8'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[12.539, 12.682, 18.936]}
//                 scale={10.904}
//               />
//               <mesh
//                 name="3DGeom-83_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-83_8'].geometry}
//                 material={materials.METAL_Chrome_Polished_Smooth1}
//                 position={[12.157, 14.584, 19.761]}
//                 scale={10.862}
//               />
//               <mesh
//                 name="3DGeom-84_8"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-84_8'].geometry}
//                 material={materials.Plastic_Black_Matte}
//                 position={[13.33, 21.532, 14.832]}
//                 scale={2.208}
//               />
//             </group>
//             <group name="door" position={[66.772, 1021.89, 15.748]} rotation={[0, 0, -Math.PI / 2]}>
//               <mesh
//                 name="3DGeom-165"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-165'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={53.524}
//               />
//               <mesh
//                 name="3DGeom-166"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-166'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={51.328}
//               />
//               <group position={[1.969, 4.366, 39.931]}>
//                 <mesh
//                   name="3DGeom-167"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-167'].geometry}
//                   material={materials.黑金色}
//                   position={[1.211, 0.624, 8.729]}
//                   scale={8.729}
//                 />
//               </group>
//             </group>
//             <group
//               name="panel"
//               position={[247.638, 122.283, 102.165]}
//               rotation={[Math.PI / 2, Math.PI / 2, 0]}>
//               <mesh
//                 name="3DGeom-168"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-168'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[0, 0, 2.953]}
//                 scale={92.52}
//               />
//               <mesh
//                 name="3DGeom-169"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-169'].geometry}
//                 material={materials['[Translucent Glass Gray]']}
//                 position={[0, 0, 2.953]}
//                 scale={90.551}
//               />
//             </group>
//             <group name="door_1" position={[466.142, 287.638, 15.748]}>
//               <mesh
//                 name="3DGeom-170"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-170'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={53.524}
//               />
//               <mesh
//                 name="3DGeom-171"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-171'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={51.328}
//               />
//               <group position={[1.969, 4.366, 39.931]}>
//                 <mesh
//                   name="3DGeom-172"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-172'].geometry}
//                   material={materials.黑金色}
//                   position={[1.211, 0.624, 8.729]}
//                   scale={8.729}
//                 />
//               </group>
//             </group>
//             <group name="r-door" position={[466.142, 251.654, 15.748]}>
//               <mesh
//                 name="3DGeom-173"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-173'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={51.328}
//               />
//               <mesh
//                 name="3DGeom-174"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-174'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={53.524}
//               />
//               <group position={[1.969, 30.626, 39.931]}>
//                 <mesh
//                   name="3DGeom-175"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-175'].geometry}
//                   material={materials.黑金色}
//                   position={[1.211, 0.624, 8.729]}
//                   scale={8.729}
//                 />
//               </group>
//             </group>
//             <group name="r-door_1" position={[354.331, 901.26, 15.748]}>
//               <mesh
//                 name="3DGeom-176"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-176'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={51.328}
//               />
//               <mesh
//                 name="3DGeom-177"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-177'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={53.524}
//               />
//               <group position={[1.969, 30.626, 39.931]}>
//                 <mesh
//                   name="3DGeom-178"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-178'].geometry}
//                   material={materials.黑金色}
//                   position={[1.211, 0.624, 8.729]}
//                   scale={8.729}
//                 />
//               </group>
//             </group>
//             <group name="door_2" position={[354.331, 937.244, 15.748]}>
//               <mesh
//                 name="3DGeom-179"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-179'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={53.524}
//               />
//               <mesh
//                 name="3DGeom-180"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-180'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={51.328}
//               />
//               <group position={[1.969, 4.366, 39.931]}>
//                 <mesh
//                   name="3DGeom-181"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-181'].geometry}
//                   material={materials.黑金色}
//                   position={[1.211, 0.624, 8.729]}
//                   scale={8.729}
//                 />
//               </group>
//             </group>
//             <group position={[231.954, 766.894, 69.272]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
//               <mesh
//                 name="3DGeom-182"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-182'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[0, 0, 2.953]}
//                 scale={53.524}
//               />
//               <group position={[0, 0, 2.953]}>
//                 <mesh
//                   name="3DGeom-183"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-183'].geometry}
//                   material={materials['[0135_DarkGray]']}
//                   scale={51.555}
//                 />
//               </group>
//             </group>
//             <group position={[143.622, 1057.323, 102.165]} rotation={[Math.PI / 2, 0, 0]}>
//               <mesh
//                 name="3DGeom-184"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-184'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[0, 0, 2.953]}
//                 scale={86.417}
//               />
//               <group position={[0, 0, 2.953]}>
//                 <mesh
//                   name="3DGeom-185"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-185'].geometry}
//                   material={materials['[Translucent Glass Gray]']}
//                   scale={84.449}
//                 />
//               </group>
//             </group>
//             <group
//               name="door_3"
//               position={[176.614, 1055.354, 15.748]}
//               rotation={[0, 0, -Math.PI / 2]}>
//               <mesh
//                 name="3DGeom-186"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-186'].geometry}
//                 material={materials['[0136_Charcoal]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={53.524}
//               />
//               <mesh
//                 name="3DGeom-187"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-187'].geometry}
//                 material={materials['[0135_DarkGray]']}
//                 position={[1.969, 17.992, 53.524]}
//                 scale={51.328}
//               />
//               <group position={[1.969, 4.366, 39.931]}>
//                 <mesh
//                   name="3DGeom-188"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-188'].geometry}
//                   material={materials.黑金色}
//                   position={[1.211, 0.624, 8.729]}
//                   scale={8.729}
//                 />
//               </group>
//             </group>
//             <group position={[358.268, 663.622, 15.748]}>
//               <mesh
//                 name="3DGeom-189"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-189'].geometry}
//                 material={materials['[0043_SaddleBrown]']}
//                 position={[9.843, 49.213, 73.209]}
//                 scale={73.209}
//               />
//               <mesh
//                 name="3DGeom-190"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-190'].geometry}
//                 material={materials['[0042_Sienna]']}
//                 position={[9.843, 49.213, 73.209]}
//                 scale={73.209}
//               />
//               <group position={[3.937, 98.425, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
//                 <mesh
//                   name="3DGeom-191"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-191'].geometry}
//                   material={materials['[0043_SaddleBrown]']}
//                   position={[49.213, -59.429, 0.591]}
//                   scale={59.429}
//                 />
//               </group>
//             </group>
//             <group position={[354.467, -266.975, -0.976]}>
//               <mesh
//                 name="3DGeom-192"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-192'].geometry}
//                 material={materials['[0022_Maroon]']}
//                 position={[-349.554, 1247.968, 73.11]}
//                 scale={58.338}
//               />
//             </group>
//             <group name="brick" position={[464.173, 517.953, 122.795]} scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-193"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-193'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group
//               name="brick_1"
//               position={[391.339, 640, 122.795]}
//               rotation={[0, 0, Math.PI / 2]}
//               scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-194"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-194'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_2" position={[121.654, 557.323, 130.472]} rotation={[0, 0, Math.PI]}>
//               <mesh
//                 name="3DGeom-195"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-195'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group
//               name="brick_3"
//               position={[450.394, 640, 122.795]}
//               rotation={[0, 0, Math.PI / 2]}
//               scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-196"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-196'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_4" position={[464.173, 557.323, 122.795]} scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-197"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-197'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_5" position={[464.173, 577.008, 122.795]} scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-198"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-198'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_6" position={[121.654, 285.669, 91.102]} rotation={[0, 0, Math.PI]}>
//               <mesh
//                 name="3DGeom-199"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-199'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_7" position={[121.654, 409.685, 130.472]} rotation={[0, 0, Math.PI]}>
//               <mesh
//                 name="3DGeom-200"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-200'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group
//               name="brick_8"
//               position={[411.024, 640, 122.795]}
//               rotation={[0, 0, Math.PI / 2]}
//               scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-201"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-201'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_9" position={[121.654, 596.693, 130.472]} rotation={[0, 0, Math.PI]}>
//               <mesh
//                 name="3DGeom-202"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-202'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group
//               name="brick_10"
//               position={[121.654, 449.055, 130.472]}
//               rotation={[0, 0, Math.PI]}>
//               <mesh
//                 name="3DGeom-203"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-203'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_11" position={[464.173, 596.693, 122.795]} scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-204"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-204'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group
//               name="brick_12"
//               position={[121.654, 488.425, 130.472]}
//               rotation={[0, 0, Math.PI]}>
//               <mesh
//                 name="3DGeom-205"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-205'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_13" position={[464.173, 537.638, 122.795]} scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-206"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-206'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group
//               name="brick_14"
//               position={[430.709, 640, 122.795]}
//               rotation={[0, 0, Math.PI / 2]}
//               scale={[1, 0.5, 0.5]}>
//               <mesh
//                 name="3DGeom-207"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-207'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group name="brick_15" position={[121.654, 350.63, 130.472]} rotation={[0, 0, Math.PI]}>
//               <mesh
//                 name="3DGeom-208"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-208'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//             <group
//               name="brick_16"
//               position={[121.654, 636.063, 130.472]}
//               rotation={[0, 0, Math.PI]}>
//               <mesh
//                 name="3DGeom-209"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-209'].geometry}
//                 material={materials['*23']}
//                 position={[2.953, 19.685, 19.685]}
//                 scale={19.685}
//               />
//             </group>
//           </group>
//                )}
//                 {visibleFloors.includes('roof') && (
//           <group name="roof" position={[-6676.251, -15432.291, 4790]} scale={25.4}>
//             <mesh
//               name="3DGeom-210"
//               castShadow
//               receiveShadow
//               geometry={nodes['3DGeom-210'].geometry}
//               material={materials['*19']}
//               position={[220.591, 345.472, 39.37]}
//               scale={345.472}
//             />
//             <mesh
//               name="3DGeom-211"
//               castShadow
//               receiveShadow
//               geometry={nodes['3DGeom-211'].geometry}
//               material={materials['[0023_FireBrick]']}
//               position={[220.591, 345.472, 55.118]}
//               scale={345.472}
//             />
//             <group position={[-107.521, 651.575, -5.135]}>
//               <mesh
//                 name="3DGeom-212"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-212'].geometry}
//                 material={materials['*19']}
//                 position={[228.017, 324.921, 98.032]}
//                 scale={324.921}
//               />
//               <mesh
//                 name="3DGeom-213"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-213'].geometry}
//                 material={materials['[0023_FireBrick]']}
//                 position={[228.006, 324.921, 98.032]}
//                 scale={324.921}
//               />
//               <group position={[212.521, 324.921, 118.722]} rotation={[0, 1.57, 1.571]}>
//                 <mesh
//                   name="3DGeom-214"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes['3DGeom-214'].geometry}
//                   material={materials['[0042_Sienna]']}
//                   position={[0, 0, 2.953]}
//                   scale={277.677}
//                 />
//               </group>
//             </group>
//             <group position={[220.591, 690.945, 110.236]} rotation={[0, 0.343, 0]}>
//               <mesh
//                 name="3DGeom-215"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-215'].geometry}
//                 material={materials['[0023_FireBrick]']}
//                 position={[117.111, -345.472, 0.984]}
//                 scale={345.472}
//               />
//             </group>
//             <group position={[0, 690.945, 31.496]} rotation={[0, -0.343, 0]}>
//               <mesh
//                 name="3DGeom-216"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-216'].geometry}
//                 material={materials['[0023_FireBrick]']}
//                 position={[117.111, -345.472, 0.984]}
//                 scale={345.472}
//               />
//             </group>
//             <group position={[110.917, 690.945, 89.768]} rotation={[0, 0.264, 0]}>
//               <mesh
//                 name="3DGeom-217"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-217'].geometry}
//                 material={materials['[0023_FireBrick]']}
//                 position={[123.038, 305.236, 0.984]}
//                 scale={305.236}
//               />
//             </group>
//             <group position={[144.204, 651.575, 190.929]} rotation={[0, -0.562, -Math.PI]}>
//               <mesh
//                 name="3DGeom-218"
//                 castShadow
//                 receiveShadow
//                 geometry={nodes['3DGeom-218'].geometry}
//                 material={materials['[0023_FireBrick]']}
//                 position={[148.703, -324.921, 0.984]}
//                 scale={324.921}
//               />
//             </group>
//           </group>
//            )}
//         </group>
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/glb/supply and procurement office output.glb')
