

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}

export function StudentCenter({visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props)  {
  const { nodes, materials } = useGLTF('/studentcenter10000 - Copy.gltf') as any
  return (
    <group  {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null} position={[-128,-2,-22]}  rotation={[0,-Math.PI / 8, 0, ]}>
      <group>
        <mesh
          name="root"
          castShadow
          receiveShadow
          geometry={nodes.root.geometry}
          material={materials['default material']}>

            {visibleFloors.includes('2ND') && (
          <group name="2ND">
            <mesh
              name="mesh_0"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0.geometry}
              material={materials['0128_White']}
            />
            <mesh
              name="mesh_0_1"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_1.geometry}
              material={materials['0012_Bisque']}
            />
            <mesh
              name="mesh_0_2"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_2.geometry}
              material={materials['0021_DarkRed']}
            />
            <mesh
              name="mesh_0_3"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_3.geometry}
              material={materials['[0136_Charcoal]2']}
            />
            <mesh
              name="mesh_0_4"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_4.geometry}
              material={materials['0111_SlateGray']}
            />
            <mesh
              name="mesh_0_5"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_5.geometry}
              material={materials['0129_WhiteSmoke']}
            />
            <mesh
              name="mesh_0_6"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_6.geometry}
              material={materials['[White Square Tile]1']}
            />
            <mesh
              name="mesh_0_7"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_7.geometry}
              material={materials['[0043_SaddleBrown]1']}
            />
            <mesh
              name="mesh_0_8"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_8.geometry}
              material={materials['Translucent Glass Gray']}
            />
            <mesh
              name="mesh_0_9"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_9.geometry}
              material={materials['0041_Chocolate']}
            />
            <mesh
              name="mesh_0_10"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_10.geometry}
              material={materials['0075_ForestGreen']}
            />
            <mesh
              name="mesh_0_11"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_11.geometry}
              material={materials['0051_Cornsilk']}
            />
            <mesh
              name="mesh_0_12"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_12.geometry}
              material={materials['0043_SaddleBrown']}
            />
            <mesh
              name="mesh_0_13"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_13.geometry}
              material={materials['Wood Veneer 01']}
            />
            <mesh
              name="mesh_0_14"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_14.geometry}
              material={materials['0131_Silver']}
            />
            <mesh
              name="mesh_0_15"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_15.geometry}
              material={materials['Material~1']}
            />
            <mesh
              name="mesh_0_16"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_16.geometry}
              material={materials['Material~10']}
            />
            <mesh
              name="mesh_0_17"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_17.geometry}
              material={materials.Aluminum_Polished}
            />
            <mesh
              name="mesh_0_18"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_18.geometry}
              material={materials['Material~8']}
            />
            <mesh
              name="mesh_0_19"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_19.geometry}
              material={materials['Material~3']}
            />
            <mesh
              name="mesh_0_20"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_20.geometry}
              material={materials['Material~']}
            />
            <mesh
              name="mesh_0_21"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_21.geometry}
              material={materials['Material~12']}
            />
            <mesh
              name="mesh_0_22"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_22.geometry}
              material={materials['Suede Dark Gray']}
            />
            <mesh
              name="mesh_0_23"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_23.geometry}
              material={materials['0023_FireBrick']}
            />
            <mesh
              name="mesh_0_24"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_24.geometry}
              material={materials['[0133_Gray]1']}
            />
            <mesh
              name="mesh_0_25"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_25.geometry}
              material={materials['Material~13']}
            />
            <mesh
              name="mesh_0_26"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_26.geometry}
              material={materials['0135_DarkGray']}
            />
            <mesh
              name="mesh_0_27"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_27.geometry}
              material={materials['0134_DimGray']}
            />
            <mesh
              name="mesh_0_28"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_28.geometry}
              material={materials['0132_LightGray']}
            />
            <mesh
              name="mesh_0_29"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_29.geometry}
              material={materials['Wood Bamboo']}
            />
            <mesh
              name="mesh_0_30"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_30.geometry}
              material={materials.Color_008}
            />
            <mesh
              name="mesh_0_31"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_31.geometry}
              material={materials['[Color_007]1']}
            />
            <mesh
              name="mesh_0_32"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_32.geometry}
              material={materials['[Metal_Corrogated_Shiny]5']}
            />
            <mesh
              name="mesh_0_33"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_33.geometry}
              material={materials['[Color_005]1']}
            />
            <mesh
              name="mesh_0_34"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_34.geometry}
              material={materials['[Color_006]2']}
            />
            <mesh
              name="mesh_0_35"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_35.geometry}
              material={materials['[Color_009]2']}
            />
            <mesh
              name="mesh_0_36"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_36.geometry}
              material={materials['0098_DodgerBlue']}
            />
            <mesh
              name="mesh_0_37"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_37.geometry}
              material={materials.Sandstone}
            />
            <mesh
              name="mesh_0_38"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_38.geometry}
              material={materials['Wood Cherry Original']}
            />
            <mesh
              name="mesh_0_39"
              castShadow
              receiveShadow
              geometry={nodes.mesh_0_39.geometry}
              material={materials['Wood Lumber ButtJoined']}
            />
          </group>
          )}
          {visibleFloors.includes('1ST') && (
          <group name="1ST">
            <mesh
              name="mesh_1"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1.geometry}
              material={materials['0012_Bisque']}
            />
            <mesh
              name="mesh_1_1"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_1.geometry}
              material={materials['0128_White']}
            />
            <mesh
              name="mesh_1_2"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_2.geometry}
              material={materials['0134_DimGray']}
            />
            <mesh
              name="mesh_1_3"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_3.geometry}
              material={materials['Field Rectangle Tile']}
            />
            <mesh
              name="mesh_1_4"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_4.geometry}
              material={materials['[0043_SaddleBrown]1']}
            />
            <mesh
              name="mesh_1_5"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_5.geometry}
              material={materials['0111_SlateGray']}
            />
            <mesh
              name="mesh_1_6"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_6.geometry}
              material={materials['0041_Chocolate']}
            />
            <mesh
              name="mesh_1_7"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_7.geometry}
              material={materials['0075_ForestGreen']}
            />
            <mesh
              name="mesh_1_8"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_8.geometry}
              material={materials['Translucent Glass Gray']}
            />
            <mesh
              name="mesh_1_9"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_9.geometry}
              material={materials['[0136_Charcoal]2']}
            />
            <mesh
              name="mesh_1_10"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_10.geometry}
              material={materials['0021_DarkRed']}
            />
            <mesh
              name="mesh_1_11"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_11.geometry}
              material={materials['0013_LightCoral']}
            />
            <mesh
              name="mesh_1_12"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_12.geometry}
              material={materials['0131_Silver']}
            />
            <mesh
              name="mesh_1_13"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_13.geometry}
              material={materials['0051_Cornsilk']}
            />
            <mesh
              name="mesh_1_14"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_14.geometry}
              material={materials['0043_SaddleBrown']}
            />
            <mesh
              name="mesh_1_15"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_15.geometry}
              material={materials['Wood Veneer 01']}
            />
            <mesh
              name="mesh_1_16"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_16.geometry}
              material={materials['[White Square Tile]2']}
            />
            <mesh
              name="mesh_1_17"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_17.geometry}
              material={materials['[White Square Tile]1']}
            />
            <mesh
              name="mesh_1_18"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_18.geometry}
              material={materials['0132_LightGray']}
            />
            <mesh
              name="mesh_1_19"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_19.geometry}
              material={materials['0042_Sienna']}
            />
            <mesh
              name="mesh_1_20"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_20.geometry}
              material={materials['<auto>4']}
            />
            <mesh
              name="mesh_1_21"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_21.geometry}
              material={materials['<auto>']}
            />
            <mesh
              name="mesh_1_22"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_22.geometry}
              material={materials['Color M07']}
            />
            <mesh
              name="mesh_1_23"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_23.geometry}
              material={materials['Material~1']}
            />
            <mesh
              name="mesh_1_24"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_24.geometry}
              material={materials['Material~10']}
            />
            <mesh
              name="mesh_1_25"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_25.geometry}
              material={materials.Aluminum_Polished}
            />
            <mesh
              name="mesh_1_26"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_26.geometry}
              material={materials['Material~8']}
            />
            <mesh
              name="mesh_1_27"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_27.geometry}
              material={materials['Material~3']}
            />
            <mesh
              name="mesh_1_28"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_28.geometry}
              material={materials['Material~']}
            />
            <mesh
              name="mesh_1_29"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_29.geometry}
              material={materials.Metal_Corrogated_Shiny}
            />
            <mesh
              name="mesh_1_30"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_30.geometry}
              material={materials.Material7}
            />
            <mesh
              name="mesh_1_31"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_31.geometry}
              material={materials.Material6}
            />
            <mesh
              name="mesh_1_32"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_32.geometry}
              material={materials.Color_A04}
            />
            <mesh
              name="mesh_1_33"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_33.geometry}
              material={materials['<DarkKhaki>']}
            />
            <mesh
              name="mesh_1_34"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_34.geometry}
              material={materials.CUZ1R}
            />
            <mesh
              name="mesh_1_35"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_35.geometry}
              material={materials['[Fencing_Mesh_Blue]1']}
            />
            <mesh
              name="mesh_1_36"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_36.geometry}
              material={materials.Color_007}
            />
            <mesh
              name="mesh_1_37"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_37.geometry}
              material={materials['Metal Silver']}
            />
            <mesh
              name="mesh_1_38"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_38.geometry}
              material={materials.Material3}
            />
            <mesh
              name="mesh_1_39"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_39.geometry}
              material={materials.Material31}
            />
            <mesh
              name="mesh_1_40"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_40.geometry}
              material={materials.Carpet_Plush_Charcoal}
            />
            <mesh
              name="mesh_1_41"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_41.geometry}
              material={materials.Material30}
            />
            <mesh
              name="mesh_1_42"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_42.geometry}
              material={materials.keyboard_laptop}
            />
            <mesh
              name="mesh_1_43"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_43.geometry}
              material={materials['<Charcoal>1']}
            />
            <mesh
              name="mesh_1_44"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_44.geometry}
              material={materials['<Gray3>']}
            />
            <mesh
              name="mesh_1_45"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_45.geometry}
              material={materials['0085_Turquoise']}
            />
            <mesh
              name="mesh_1_46"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_46.geometry}
              material={materials['0010_Snow']}
            />
            <mesh
              name="mesh_1_47"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_47.geometry}
              material={materials['Material~12']}
            />
            <mesh
              name="mesh_1_48"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_48.geometry}
              material={materials['Suede Dark Gray']}
            />
            <mesh
              name="mesh_1_49"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_49.geometry}
              material={materials['0023_FireBrick']}
            />
            <mesh
              name="mesh_1_50"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_50.geometry}
              material={materials['[0133_Gray]1']}
            />
            <mesh
              name="mesh_1_51"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_51.geometry}
              material={materials['Material~13']}
            />
            <mesh
              name="mesh_1_52"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_52.geometry}
              material={materials['0137_Black']}
            />
            <mesh
              name="mesh_1_53"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_53.geometry}
              material={materials['[0021_DarkRed]1']}
            />
            <mesh
              name="mesh_1_54"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_54.geometry}
              material={materials['0022_Maroon']}
            />
            <mesh
              name="mesh_1_55"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_55.geometry}
              material={materials['0045_Goldenrod']}
            />
            <mesh
              name="mesh_1_56"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_56.geometry}
              material={materials.Material17}
            />
            <mesh
              name="mesh_1_57"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_57.geometry}
              material={materials['Quartz Light Grey']}
            />
            <mesh
              name="mesh_1_58"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_58.geometry}
              material={materials['0104_MediumBlue']}
            />
            <mesh
              name="mesh_1_59"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_59.geometry}
              material={materials['[Color_008]1']}
            />
            <mesh
              name="mesh_1_60"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_60.geometry}
              material={materials['0129_WhiteSmoke']}
            />
            <mesh
              name="mesh_1_61"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_61.geometry}
              material={materials['0135_DarkGray']}
            />
            <mesh
              name="mesh_1_62"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_62.geometry}
              material={materials['0011_Seashell']}
            />
            <mesh
              name="mesh_1_63"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_63.geometry}
              material={materials['<Black>1']}
            />
            <mesh
              name="mesh_1_64"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_64.geometry}
              material={materials['<Charcoal>2']}
            />
            <mesh
              name="mesh_1_65"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_65.geometry}
              material={materials['<Silver>']}
            />
            <mesh
              name="mesh_1_66"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_66.geometry}
              material={materials.Color_008}
            />
            <mesh
              name="mesh_1_67"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_67.geometry}
              material={materials['[Color_007]1']}
            />
            <mesh
              name="mesh_1_68"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_68.geometry}
              material={materials['[Metal_Corrogated_Shiny]5']}
            />
            <mesh
              name="mesh_1_69"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_69.geometry}
              material={materials['[Color_005]1']}
            />
            <mesh
              name="mesh_1_70"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_70.geometry}
              material={materials['[Color_006]2']}
            />
            <mesh
              name="mesh_1_71"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_71.geometry}
              material={materials['[Color_009]2']}
            />
            <mesh
              name="mesh_1_72"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_72.geometry}
              material={materials['0098_DodgerBlue']}
            />
            <mesh
              name="mesh_1_73"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_73.geometry}
              material={materials['68e88268_e646_4db8_bad9_8a3760e13a95']}
            />
            <mesh
              name="mesh_1_74"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_74.geometry}
              material={materials['0095_LightBlue']}
            />
            <mesh
              name="mesh_1_75"
              castShadow
              receiveShadow
              geometry={nodes.mesh_1_75.geometry}
              material={materials['Wood Cherry Original']}
            />
          </group>
          )}
           {visibleFloors.includes('roof') && (
          <group name="roof">
            <mesh
              name="mesh_2"
              castShadow
              receiveShadow
              geometry={nodes.mesh_2.geometry}
              material={materials['0012_Bisque']}
            />
            <mesh
              name="mesh_2_1"
              castShadow
              receiveShadow
              geometry={nodes.mesh_2_1.geometry}
              material={materials['0021_DarkRed']}
            />
            <mesh
              name="mesh_2_2"
              castShadow
              receiveShadow
              geometry={nodes.mesh_2_2.geometry}
              material={materials['0023_FireBrick']}
            />
          </group>
          )}

        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/studentcenter10000 - Copy.gltf')
