/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
type Props = {
  selected?: boolean
  onSelect?: (id: string) => void
  onClick?: () => void
  visibleFloors?: string[]
}
export function TennisCourt({ visibleFloors = ["1ST", "2ND", "roof"], selected, onSelect, onClick, ...props }: Props) {
  const { nodes, materials } = useGLTF('/tennis court.glb') as any;
  return (
    <group  {...props}
      onClick={(e) => {
        e.stopPropagation()
        onClick?.()
      }}  dispose={null}  position={[100,0,-180]} rotation={[0, -Math.PI / 1.60 , 0, ]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.001}>
          <group position={[15025.079, 16096.511, 20]} scale={[25.4, 19.757, 25.4]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-2'].geometry}
              material={materials['*1']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-3'].geometry}
              material={materials['*3']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-4'].geometry}
              material={materials['*2']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-5'].geometry}
              material={materials['[0129_WhiteSmoke]']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-6'].geometry}
              material={materials['*4']}
            />
          </group>
          <group position={[15001.359, 3873.972, 20]} scale={[25.4, 19.757, 25.4]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-2_1'].geometry}
              material={materials['*1']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-3_1'].geometry}
              material={materials['*3']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-4_1'].geometry}
              material={materials['*2']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-5_1'].geometry}
              material={materials['[0129_WhiteSmoke]']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-6_1'].geometry}
              material={materials['*4']}
            />
          </group>
          <group position={[0, -2000, 0]} scale={25.4}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-12'].geometry}
              material={materials['[Polished Concrete Old]']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-13'].geometry}
              material={materials['[0086_MediumAquamarine]']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3DGeom-14'].geometry}
              material={materials['[0134_DimGray]']}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['3DGeom-1'].geometry}
            material={materials['[0019_Crimson]']}
            scale={25.4}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tennis court.glb')
